In [1]:
import sqlite3

db_file = "/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/database/SMART.db"

conn = sqlite3.connect(db_file)
cursor = conn.cursor()

# Get all user tables
cursor.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type='table'
      AND name NOT LIKE 'sqlite_%'
    ORDER BY name
""")

tables = [row[0] for row in cursor.fetchall()]

for table in tables:
    print(f"\nTable: {table}")

    cursor.execute(f"PRAGMA table_info('{table}')")
    columns = cursor.fetchall()

    for col in columns:
        # col format:
        # (cid, name, type, notnull, dflt_value, pk)
        print(f"  {col[1]} ({col[2]})")

conn.close()

Table: ip_addresses
  id (CHAR(32))
  ip_address (TEXT)
  rdns_hostname (TEXT)
  asn (INTEGER)
  asn_org (TEXT)
  country_code (TEXT)
  country_rating (INTEGER)
  asn_rating (INTEGER)

Table: mail_system_ip_history
  id (CHAR(32))
  mail_system_id (CHAR(32))
  ip_address_id (CHAR(32))
  valid_from_run (CHAR(32))
  valid_to_run (CHAR(32))
  is_current (BOOLEAN)

Table: mail_systems
  id (CHAR(32))
  role (VARCHAR(9))
  software (TEXT)
  vendor (TEXT)
  vendor_country (TEXT)
  vendor_category (TEXT)
  vendor_country_rating (INTEGER)
  open_source_rating (INTEGER)
  vendor_category_rating (INTEGER)

Table: org_domain_history
  id (CHAR(32))
  organisation_id (CHAR(32))
  valid_from_run (CHAR(32))
  valid_to_run (CHAR(32))
  is_current (BOOLEAN)
  email_domain (TEXT)
  website_domain (TEXT)

Table: org_mail_system_history
  id (CHAR(32))
  organisation_id (CHAR(32))
  mail_system_id (CHAR(32))
  valid_from_run (CHAR(32))
  valid_to_run (CHAR(32))
  proxy_system_id (CHAR(32))
  is_current (BOOLEAN)

Table: organisations
  id (CHAR(32))
  name (TEXT)
  wikidata_url (TEXT)
  city (TEXT)
  state (TEXT)
  country (TEXT)
  category_tag (TEXT)
  longitude (REAL)
  latitude (REAL)
  website (TEXT)

Table: scanner_runs
  id (CHAR(32))
  started_at (TIMESTAMP)
  finished_at (TIMESTAMP)
  scanner_version_git_hash (TEXT)

In [1]:
import pandas as pd
path = "/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/exports"
smtp = pd.read_csv(path+"/smtp.csv")
smtp

,mx_domain,smtp_banner,port,error
0,mx2.belwue.de,220 mail-in02.belwue.de ESMTP Postfix,25.0,NaN
1,mx3.belwue.de,220 mail-in03.belwue.de ESMTP Postfix,25.0,NaN
2,mx1.belwue.de,220 mail-in02.belwue.de ESMTP Postfix,25.0,NaN
3,mx4.belwue.de,220 mail-in04.belwue.de ESMTP Postfix,25.0,NaN
4,burg-halle.de,220 ******************************************...,25.0,NaN
...,...,...,...,...
2925,wels-gv-at.mail.eo.outlook.com,220 AM3PEPF0000A790.mail.protection.outlook.co...,25.0,NaN
2926,laakirchen-ooe-gv-at.mail.protection.outlook.com,220 VI4PEPF00000001.mail.protection.outlook.co...,25.0,NaN
2927,msx1.salzburg.gv.at,554-msx2.salzburg.gv.at,25.0,NaN
2928,mx2.hc1656-87.eu.iphmx.com,220 esa2.hc1656-87.eu.iphmx.com ESMTP,25.0,NaN
2929,mx1.hc1656-87.eu.iphmx.com,220 esa1.hc1656-87.eu.iphmx.com ESMTP,25.0,NaN

In [15]:
ignore = ["220", "Fri,", "Jun", "at", "2026", "ready", "19", "+0200", "+0000", "-"]

keywords = (
    smtp["smtp_banner"]
    .str.split()
    .explode()
    .loc[lambda s: ~s.isin(ignore)]
    .value_counts()
)
keywords

smtp_banner
ESMTP                                          2057
Postfix                                         527
Service                                         461
Microsoft                                       373
MAIL                                            373
                                               ...
VI4PEPF00000001.mail.protection.outlook.com       1
[08DEC92A93255CD6]                                1
554-msx2.salzburg.gv.at                           1
esa2.hc1656-87.eu.iphmx.com                       1
esa1.hc1656-87.eu.iphmx.com                       1
Name: count, Length: 3100, dtype: int64

In [3]:
import re
import yaml
from dataclasses import dataclass
from typing import Any


@dataclass
class MatchResult:
    banner: str
    software: str | None = None
    vendor: str | None = None
    vendor_country: str | None = None
    vendor_category: str | None = None
    regex: str | None = None


def load_yaml(path: str) -> list[dict]:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def apply_rules(banners: list[str], rules: list[dict]) -> tuple[list[MatchResult], list[str]]:
    remaining = banners[:]
    results: list[MatchResult] = []

    for rule in rules:
        regex = re.compile(rule["regex"])

        still_remaining = []

        for banner in remaining:
            if regex.search(banner):
                results.append(
                    MatchResult(
                        banner=banner,
                        software=rule.get("software"),
                        vendor=rule.get("vendor"),
                        vendor_country=rule.get("vendor_country"),
                        vendor_category=rule.get("vendor_category"),
                        regex=rule["regex"],
                    )
                )
            else:
                still_remaining.append(banner)

        remaining = still_remaining

    return results, remaining

import pandas as pd
import re
from collections import Counter
from typing import List, Optional, Set


def extract_keywords(
    domains: List[str],
    remove_tlds: Optional[Set[str]] = None
) -> pd.DataFrame:
    """
    Extract keywords from domain list and return frequency table.
    
    Parameters:
    - domains: list of domain strings
    - remove_tlds: set like {".de", ".com"} to filter out TLD tokens
    
    Returns:
    - DataFrame with columns: keyword, count
    """

    counter = Counter()

    for domain in domains:
        domain = domain.lower().strip()

        # split by special characters
        parts = re.split(r"[.\-_/]", domain)

        for part in parts:
            part = part.strip()

            if not part:
                continue

            # filter TLDs if needed
            if remove_tlds and part in remove_tlds:
                continue

            # remove numeric-only or garbage tokens
            if part.isdigit():
                continue

            counter[part] += 1

    df = pd.DataFrame(counter.items(), columns=["keyword", "count"])
    df = df.sort_values("count", ascending=False).reset_index(drop=True)

    return df

In [18]:
pd.DataFrame(matches)

,banner,software,vendor,vendor_country,vendor_category,regex
0,220 mx-ber.mail-bz.de - NoSpamProxy ready,NoSpamProxy,Net at Work GmbH,DE,Security / Proxy (EU Vendor),(?i)nospamproxy
1,220 mx-hh.mail-bz.de - NoSpamProxy ready,NoSpamProxy,Net at Work GmbH,DE,Security / Proxy (EU Vendor),(?i)nospamproxy
2,220 dhpolpost.dhpol.de - NoSpamProxy ready,NoSpamProxy,Net at Work GmbH,DE,Security / Proxy (EU Vendor),(?i)nospamproxy
3,220 mx.bu-jordan.de - NoSpamProxy ready,NoSpamProxy,Net at Work GmbH,DE,Security / Proxy (EU Vendor),(?i)nospamproxy
4,220 mailin.campus-lb.net - NoSpamProxy ready,NoSpamProxy,Net at Work GmbH,DE,Security / Proxy (EU Vendor),(?i)nospamproxy
...,...,...,...,...,...,...
1172,220-pmg.amtruhland.local ESMTP Proxmox,Proxmox Mail Gateway,Proxmox Server Solutions GmbH,AT,EU-Mailsoftware-Anbieter,(?i)proxmox
1173,220-mx1.lychen.de ESMTP Proxmox,Proxmox Mail Gateway,Proxmox Server Solutions GmbH,AT,EU-Mailsoftware-Anbieter,(?i)proxmox
1174,220-mailgw.teterow.de ESMTP Proxmox,Proxmox Mail Gateway,Proxmox Server Solutions GmbH,AT,EU-Mailsoftware-Anbieter,(?i)proxmox
1175,220-mailgate.halberstadt.de ESMTP Proxmox,Proxmox Mail Gateway,Proxmox Server Solutions GmbH,AT,EU-Mailsoftware-Anbieter,(?i)proxmox
1176,220-pmg.bernsdorf.de ESMTP Proxmox,Proxmox Mail Gateway,Proxmox Server Solutions GmbH,AT,EU-Mailsoftware-Anbieter,(?i)proxmox

In [20]:
rules = load_yaml("/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/src/signatures_pipeline/signatures/smtp.yaml")

banners = smtp["smtp_banner"].dropna().tolist()

matches, unmatched = apply_rules(banners, rules)
print(f"Coverage: {len(matches)/len(banners)}")
unmatched

result = extract_keywords(
    unmatched,
    remove_tlds={"de", "mail", "mx"}
)
result

Coverage: 0.43608743979251574

                                             keyword  count
0                                           220 mail    268
1                                           de esmtp    145
2                                     de esmtp ready    145
3                                          com esmtp    100
4                                                ess     64
...                                              ...    ...
1985                                    220 hermes32      1
1986                                    220 hermes31      1
1987                                    220 kliniken      1
1988  (c) mailsheriff esmtp service ready to connect      1
1989                                     local esmtp      1

[1990 rows x 2 columns]

In [2]:
import pandas as pd
path = "/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/exports"
asn = pd.read_csv(path+"/asn.csv")
combiner = pd.read_csv(path+"/combiner.csv")
domain = pd.read_csv(path+"/domain.csv")
imap = pd.read_csv(path+"/imap.csv")
ip = pd.read_csv(path+"/ip.csv")
mx = pd.read_csv(path+"/mx.csv")
smtp = pd.read_csv(path+"/smtp.csv")
ptr = pd.read_csv(path+"/ptr.csv")
domain

,id,organisation_id,valid_from_run,valid_to_run,is_current,email_domain,website_domain
0,276a3ae08ea045a9977a9345b110f5ba,a87f2eaab2a344afa905735b429fc142,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,dhbw-loerrach.de
1,cf8ed1372a90485489eb54b4d7d58292,3117434b47164a4a9833e9d2feff9fad,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,burg-halle.de
2,c491c1cd523842e7a2070f030a6e4832,3f0585cf1d844cb3894c317102413b48,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,businessschool-berlin.de
3,5590cd997d3f4724ad22ce17cc170a32,1a77dd9022f3459fa50cea34bc757033,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,cvjm-hochschule.de
4,ed694e4f09a14f52b913ab659bce93d4,80a41cd1328d4cbdac16426cbc9cb63a,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,tuhh.de
...,...,...,...,...,...,...,...
5020,bee3576183e348cc8cc897a1df4615b0,478a7d7e5446482db895bbe19fd649b7,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,bs.ch
5021,a04fd7fdcedb4c519ac8855b221a5675,f276104dde32449cbbb1cea70f89ac96,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,lausanne.ch
5022,b60a17c316754e9ca5420be3b10401a5,35dae49712034959b9fe929ac64b78ff,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,stadt-schaffhausen.ch
5023,70dff7b817694672ba802965065d3ab7,c9bb002d4f2b4a72bad9e1fa043083fd,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,buelach.ch
5024,f95308dae3534e55b51f96ee4b049c65,ca2fd6cc059846ed877cb62adaa1c206,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,winterthur.ch

In [3]:
domain

,id,organisation_id,valid_from_run,valid_to_run,is_current,email_domain,website_domain
0,276a3ae08ea045a9977a9345b110f5ba,a87f2eaab2a344afa905735b429fc142,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,dhbw-loerrach.de
1,cf8ed1372a90485489eb54b4d7d58292,3117434b47164a4a9833e9d2feff9fad,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,burg-halle.de
2,c491c1cd523842e7a2070f030a6e4832,3f0585cf1d844cb3894c317102413b48,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,businessschool-berlin.de
3,5590cd997d3f4724ad22ce17cc170a32,1a77dd9022f3459fa50cea34bc757033,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,cvjm-hochschule.de
4,ed694e4f09a14f52b913ab659bce93d4,80a41cd1328d4cbdac16426cbc9cb63a,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,tuhh.de
...,...,...,...,...,...,...,...
5020,bee3576183e348cc8cc897a1df4615b0,478a7d7e5446482db895bbe19fd649b7,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,bs.ch
5021,a04fd7fdcedb4c519ac8855b221a5675,f276104dde32449cbbb1cea70f89ac96,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,lausanne.ch
5022,b60a17c316754e9ca5420be3b10401a5,35dae49712034959b9fe929ac64b78ff,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,stadt-schaffhausen.ch
5023,70dff7b817694672ba802965065d3ab7,c9bb002d4f2b4a72bad9e1fa043083fd,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,buelach.ch
5024,f95308dae3534e55b51f96ee4b049c65,ca2fd6cc059846ed877cb62adaa1c206,6d9c5553cdfb46d4844940801a9559f4,NaN,1,NaN,winterthur.ch

In [7]:
ip

                       mx_domain                ip error
0                  mx2.belwue.de  2001:7c0:0:76::2   NaN
1                  mx2.belwue.de      129.143.76.2   NaN
2                  mx3.belwue.de  2001:7c0:0:76::3   NaN
3                  mx3.belwue.de      129.143.76.3   NaN
4                  mx1.belwue.de  2001:7c0:0:76::1   NaN
...                          ...               ...   ...
6196         msx1.salzburg.gv.at    193.41.228.254   NaN
6197  mx2.hc1656-87.eu.iphmx.com     23.90.122.224   NaN
6198  mx2.hc1656-87.eu.iphmx.com      23.90.123.49   NaN
6199  mx1.hc1656-87.eu.iphmx.com      23.90.123.49   NaN
6200  mx1.hc1656-87.eu.iphmx.com     23.90.122.224   NaN

[6201 rows x 3 columns]

In [25]:
smtp

,mx_domain,smtp_banner,port,error
0,mx2.belwue.de,220 mail-in02.belwue.de ESMTP Postfix,25.0,NaN
1,mx3.belwue.de,220 mail-in03.belwue.de ESMTP Postfix,25.0,NaN
2,mx1.belwue.de,220 mail-in02.belwue.de ESMTP Postfix,25.0,NaN
3,mx4.belwue.de,220 mail-in04.belwue.de ESMTP Postfix,25.0,NaN
4,burg-halle.de,220 ******************************************...,25.0,NaN
...,...,...,...,...
2925,wels-gv-at.mail.eo.outlook.com,220 AM3PEPF0000A790.mail.protection.outlook.co...,25.0,NaN
2926,laakirchen-ooe-gv-at.mail.protection.outlook.com,220 VI4PEPF00000001.mail.protection.outlook.co...,25.0,NaN
2927,msx1.salzburg.gv.at,554-msx2.salzburg.gv.at,25.0,NaN
2928,mx2.hc1656-87.eu.iphmx.com,220 esa2.hc1656-87.eu.iphmx.com ESMTP,25.0,NaN
2929,mx1.hc1656-87.eu.iphmx.com,220 esa1.hc1656-87.eu.iphmx.com ESMTP,25.0,NaN

In [32]:
start = mx[mx["error"].isna()].drop_duplicates("domain").drop(columns="error")

start = start.merge(
    ip.drop_duplicates(subset=["mx_domain"]),
    on="mx_domain",
    how="left",
    validate="many_to_one",   # viele Domains -> eine IP-Zeile pro mx_domain
).drop(columns="error")

start = start.merge(
    ptr.drop_duplicates(subset=["ip"]),
    on="ip",
    how="left",
    validate="many_to_one",   # viele Domains -> eine PTR-Zeile pro IP
).drop(columns="error")

start = start.merge(
    asn,
    on="ip",
    how="left",
    validate="many_to_one",   # viele Domains -> eine ASN-Zeile pro IP
).drop(columns=["ip", "prefix", "error", "asn"])

start = start.merge(
    imap.rename(columns={"banner": "imap_banner"}),
    on="domain",
    how="left",
    validate="one_to_one",    # domain sollte links und rechts eindeutig sein
).drop(columns=["error", "port"])

start = start.merge(
    smtp,
    on="mx_domain",
    how="left",
    validate="many_to_one",   # viele Domains -> eine SMTP-Zeile pro mx_domain
).drop(columns=["error", "port"])
start.to_csv("/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/exports/combined_scanning_results.csv")

In [ ]:
start = mx[mx["error"].isna()].drop_duplicates("domain").drop(columns="error")
start = start.merge(ip.drop_duplicates("mx_domain"), on="mx_domain", how="left").drop(columns="error")
start = start.merge(ptr, on="ip", how="left").drop(columns="error")
start = start.merge(asn, on="ip", how="left").drop(columns=["ip", "prefix", "error", "asn"])
start = start.merge(imap.rename(columns={"banner":"imap_banner"}), on="domain", how="left").drop(columns=["error", "port"])
start = start.merge(smtp, on="mx_domain", how="left").drop(columns=["error", "port"])
start

,domain,mx_domain,ptr,owner,country,imap_host,imap_banner,smtp_banner
0,dhbw-loerrach.de,mx2.belwue.de,mail-in02.belwue.de,"BELWUE - Universitaet Stuttgart, DE",DE,imap.dhbw-loerrach.de,* OK IMAP4 ready,220 mail-in02.belwue.de ESMTP Postfix
1,dhbw-loerrach.de,mx2.belwue.de,mail-in02.belwue.de,"BELWUE - Universitaet Stuttgart, DE",DE,imap.dhbw-loerrach.de,* OK IMAP4 ready,220 mail-in02.belwue.de ESMTP Postfix
2,burg-halle.de,burg-halle.de,burg-halle.de,"HLKOMM - HL komm Telekommunikations GmbH, DE",DE,NaN,NaN,220 ******************************************...
3,businessschool-berlin.de,mx-ber.mail-bz.de,mx-ber.mail-bz.de,"VERSATEL - 1&1 Versatel GmbH, DE",DE,NaN,NaN,220 mx-ber.mail-bz.de - NoSpamProxy ready
4,cvjm-hochschule.de,mx1.serve-me.de,mx1.serve-me.de,"HETZNER-AS - Hetzner Online GmbH, DE",DE,NaN,NaN,220 mx1.serve-me.de ESMTP
...,...,...,...,...,...,...,...,...
7163,klingenbach.bgld.gv.at,smtp.asp-bgld.at,smtp.asp-bgld.at,"KABSI-AS - kabelplus GmbH, AT",AT,NaN,NaN,"220 smtp.asp-bgld.at ESMTP Smtpd; Fri, 19 Jun ..."
7164,ktn.gde.at,mx2.hc1656-87.eu.iphmx.com,esa2.hc1656-87.eu.iphmx.com,AS-IRONP-VEGA - Cisco Systems Ironport Divisio...,US,NaN,NaN,220 esa2.hc1656-87.eu.iphmx.com ESMTP
7165,ktn.gde.at,mx2.hc1656-87.eu.iphmx.com,esa1.hc1656-87.eu.iphmx.com,AS-IRONP-VEGA - Cisco Systems Ironport Divisio...,US,NaN,NaN,220 esa2.hc1656-87.eu.iphmx.com ESMTP
7166,kittsee.bgld.gv.at,smtp.asp-bgld.at,smtp.asp-bgld.at,"KABSI-AS - kabelplus GmbH, AT",AT,NaN,NaN,"220 smtp.asp-bgld.at ESMTP Smtpd; Fri, 19 Jun ..."
7167,aesch.bl.ch,ktvmx03.mail.admin.ch,ktvmx03.mail.admin.ch,"SWISSGOV - SWISSGOV, CH",CH,NaN,NaN,"220 ktvmx03.mail.admin.ch ESMTP Smtpd; Fri, 19..."

In [2]:
import re
import yaml
from dataclasses import dataclass
from typing import Any


@dataclass
class MatchResult:
    banner: str
    software: str | None = None
    vendor: str | None = None
    vendor_country: str | None = None
    vendor_category: str | None = None
    regex: str | None = None


def load_yaml(path: str) -> list[dict]:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def apply_rules(banners: list[str], rules: list[dict]) -> tuple[list[MatchResult], list[str]]:
    remaining = banners[:]
    results: list[MatchResult] = []

    for rule in rules:
        regex = re.compile(rule["regex"])

        still_remaining = []

        for banner in remaining:
            if regex.search(banner):
                results.append(
                    MatchResult(
                        banner=banner,
                        software=rule.get("software"),
                        vendor=rule.get("vendor"),
                        vendor_country=rule.get("vendor_country"),
                        vendor_category=rule.get("vendor_category"),
                        regex=rule["regex"],
                    )
                )
            else:
                still_remaining.append(banner)

        remaining = still_remaining

    return results, remaining

In [ ]:
rules = load_yaml("/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/src/signatures_pipeline/signatures/mx.yaml")

banners = mx["mx_domain"].dropna().tolist()

matches, unmatched = apply_rules(banners, rules)
print(f"Coverage: {len(matches)/len(banners)}")
unmatched

result = extract_keywords(
    unmatched,
    remove_tlds={"de", "com", "at", "mail", "mx", "ch", "mx1", "mx2","net"}
)
result

Coverage: 0.49255014326647567

       keyword  count
0          rlp    156
1        mail2    132
2          uni    128
3         mx01    127
4           in    111
...        ...    ...
2232       bwl      1
2233  hermes32      1
2234  hermes31      1
2235    email2      1
2236    ostalb      1

[2237 rows x 2 columns]

In [42]:
import pandas as pd
import re
from collections import Counter
from typing import List, Optional, Set


def extract_keywords(
    domains: List[str],
    remove_tlds: Optional[Set[str]] = None
) -> pd.DataFrame:
    """
    Extract keywords from domain list and return frequency table.
    
    Parameters:
    - domains: list of domain strings
    - remove_tlds: set like {".de", ".com"} to filter out TLD tokens
    
    Returns:
    - DataFrame with columns: keyword, count
    """

    counter = Counter()

    for domain in domains:
        domain = domain.lower().strip()

        # split by special characters
        parts = re.split(r"[.\-_/]", domain)

        for part in parts:
            part = part.strip()

            if not part:
                continue

            # filter TLDs if needed
            if remove_tlds and part in remove_tlds:
                continue

            # remove numeric-only or garbage tokens
            if part.isdigit():
                continue

            counter[part] += 1

    df = pd.DataFrame(counter.items(), columns=["keyword", "count"])
    df = df.sort_values("count", ascending=False).reset_index(drop=True)

    return df

result = extract_keywords(
    unmatched,
    remove_tlds={"de", "com", "at", "mail", "mx", "ch", }
)
result

      keyword  count
0         mx1    201
1         mx2    189
2         net    184
3         rlp    156
4       mail2    132
...       ...    ...
2297      ooe      1
2298  braunau      1
2299  relay7m      1
2300  relay7v      1
2301      bwl      1

[2302 rows x 2 columns]

In [52]:
remaining = pd.DataFrame(unmatched, columns=["mx_domain"])
remaining["mx_domain"].value_counts()

mx_domain
sslmail.verwaltungsportal.de             65
mail.bayern.de                           64
mxlb.ispgateway.de                       45
mx-in.kommunale.it                       44
mailmx0001.rlp.de                        40
                                         ..
braunau-ooe-gv-at.gate.seppmail.cloud     1
srv-gw-mx1.magibk.at                      1
srv-gw-mx2.magibk.at                      1
wels-gv-at.mail.eo.outlook.com            1
msx1.salzburg.gv.at                       1
Name: count, Length: 2204, dtype: int64

In [15]:
matches

[MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=GSSAPI] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE XLIST SPECIAL-USE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS LOGINDISABLED AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] DOVECOT ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Ubuntu) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot (Ubuntu) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot at Uni Muenster ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Ubuntu) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot director ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot (Ubuntu) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] dOvEcOt238_uibk hIgh_peRfOrmAnCe-mAIlsErver ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE XLIST LITERAL+ STARTTLS AUTH=PLAIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),
 MatchResult(banner='* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.', software='Dovecot', vendor='Open Source', vendor_country='FI', vendor_category='Mail Server', regex='(?i)dovecot'),

In [12]:
imap["banner"].dropna().value_counts()

banner
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.                                                                                   118
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE XLIST LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] kasserver.com mailserver ready.                                                            105
* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.                                                      69
* OK The Microsoft Exchange IMAP4 service is ready.                                                                                                                                                          67
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5] Mailserver ready.                                                                   61
                                                                                                                                                                                                           ...
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] NA-NET Communications GmbH IMAP-Server.                                                            1
* OK Microsoft Exchange IMAP4 service ready. ce2aa86b-7d90-4bbc-b1df-507fdc36ec12 (tcpproxy/15.21.0159.004 BACKENDAUTHENTICATE) [RgBSADIAUAAyADgAMQBDAEEAMAAxADEANwAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4      1
* OK Microsoft Exchange IMAP4 service ready. 4c931a20-3037-44b6-9b50-ee7806db4432 (tcpproxy/15.21.0139.008 BACKENDAUTHENTICATE) [RgBSADQAUAAyADgAMQBDAEEAMAAxADQANAAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4      1
* OK Microsoft Exchange IMAP4 service ready. bd0cce63-eb6f-48a9-aeac-d2d526913e7b (tcpproxy/15.21.0159.004 BACKENDAUTHENTICATE) [RgBSADIAUAAyADgAMQBDAEEAMAAwADkANAAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4      1
* OK PopNet Informatik AG Mail Server IMAP4rev1 Fri, 19 Jun 2026 14:43:36 +0200                                                                                                                               1
Name: count, Length: 138, dtype: int64

In [4]:
combiner_mx = combiner.merge(mx, on="domain", how="left").drop(columns=["error"])
combiner_mx
combiner_mx_ip = combiner_mx.merge(ip.drop(columns=["error"]), on="mx_domain")
combiner_mx_ip
combiner_mx_ip_asn = combiner_mx_ip.merge(asn.drop(columns=["asn", "prefix", "error"]), on="ip")
combiner_mx_ip_asn
combiner_mx_ip_asn_smtp = combiner_mx_ip_asn.merge(smtp.drop(columns=["port", "error"]), on="mx_domain")
combiner_mx_ip_asn_smtp
combiner_mx_ip_asn_smtp_imap = combiner_mx_ip_asn_smtp.merge(imap.drop(columns=["port", "error"]), on="domain")
combiner_mx_ip_asn_smtp_imap
# domain_combiner_mx = domain.merge(combiner_mx, left_on="email", right_on="domain", how="left")
# domain_combiner_mx = domain.merge(combiner_mx, left_on="email", right_on="domain", how="left")
# domain_combiner_mx
# combiner_mx_domain_ip = combiner_mx_domain.merge(ip.drop(columns=["error"]), on="mx_domain", how="outer")
# combiner_mx_domain_ip

,domain,mx_domain,ip,owner,country,smtp_banner,imap_host,banner
0,dhbw-loerrach.de,mx3.belwue.de,2001:7c0:0:76::3,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in03.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
1,dhbw-loerrach.de,mx3.belwue.de,129.143.76.3,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in03.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
2,dhbw-loerrach.de,mx2.belwue.de,2001:7c0:0:76::2,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in02.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
3,dhbw-loerrach.de,mx2.belwue.de,129.143.76.2,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in02.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
4,dhbw-loerrach.de,mx1.belwue.de,2001:7c0:0:76::2,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in02.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
...,...,...,...,...,...,...,...,...
13282,zermatt.ch,zermatt-ch.mail.protection.outlook.com,2a01:111:f403:ca3c::1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN
13283,zermatt.ch,zermatt-ch.mail.protection.outlook.com,52.101.185.12,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN
13284,zermatt.ch,zermatt-ch.mail.protection.outlook.com,52.101.185.13,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN
13285,zermatt.ch,zermatt-ch.mail.protection.outlook.com,52.101.187.1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN
13286,zermatt.ch,zermatt-ch.mail.protection.outlook.com,52.101.185.14,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN

In [ ]:
temp = combiner_mx_ip_asn_smtp_imap.drop_duplicates(subset=["domain", "owner", "country"])
temp[temp["domain"].duplicated(keep=False)]

,domain,mx_domain,ip,owner,country,smtp_banner,imap_host,banner
27,university-of-labour.de,universityoflabour-de02ec.mail.protection.outl...,2a01:111:f403:ca2d::1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 FR2PEPF000004F0.mail.protection.outlook.co...,imap.university-of-labour.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
31,university-of-labour.de,universityoflabour-de02ec.mail.protection.outl...,52.101.170.1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 FR2PEPF000004F0.mail.protection.outlook.co...,imap.university-of-labour.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
39,srh-university.de,srhuniversity-de0i.mail.protection.outlook.com,2a01:111:f403:ca04::9,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 DU6PEPF0000B620.mail.protection.outlook.co...,NaN,NaN
43,srh-university.de,srhuniversity-de0i.mail.protection.outlook.com,52.101.68.39,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 DU6PEPF0000B620.mail.protection.outlook.co...,NaN,NaN
51,rptu.de,mailgate1.uni-kl.de,2001:638:208:120::208,DFN - Verein zur Foerderung eines Deutschen Fo...,DE,220 mailgw2.uni-kl.de ESMTP Sendmail 8.18.1/8....,mail.rptu.de,* OK mail1.uni-kl.de CommuniGate Pro IMAP Serv...
...,...,...,...,...,...,...,...,...
13258,steyr.gv.at,steyr-gv-at.mail.protection.outlook.com,52.101.68.8,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 AM2PEPF0001C717.mail.protection.outlook.co...,NaN,NaN
13262,laakirchen.ooe.gv.at,laakirchen-ooe-gv-at.mail.protection.outlook.com,2a01:111:f403:ca6e::3,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 VI6PEPF00000005.mail.protection.outlook.co...,NaN,NaN
13266,laakirchen.ooe.gv.at,laakirchen-ooe-gv-at.mail.protection.outlook.com,40.107.180.3,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 VI6PEPF00000005.mail.protection.outlook.co...,NaN,NaN
13279,zermatt.ch,zermatt-ch.mail.protection.outlook.com,2a01:111:f403:ca3c::2,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN
13283,zermatt.ch,zermatt-ch.mail.protection.outlook.com,52.101.185.12,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 GV1PEPF000006FB.mail.protection.outlook.co...,NaN,NaN

In [20]:
domain_email = domain[["name","email", "website_domain"]].merge(temp.drop_duplicates(subset="domain"), left_on="email", right_on="domain", how="left")

matched = domain_email[domain_email["domain"].notna()]

unmatched = (
    domain_email[domain_email["domain"].isna()]
    .drop(columns=temp.columns, errors="ignore")  # remove empty merge columns
    .merge(temp, left_on="website_domain", right_on="domain", how="left")
)

final = pd.concat([matched, unmatched], ignore_index=True).drop_duplicates("name")
final

,name,email,website_domain,domain,mx_domain,ip,owner,country,smtp_banner,imap_host,banner
0,CVJM-Hochschule,cvjm.de,cvjm-hochschule.de,cvjm.de,cvjm-de.mail.protection.outlook.com,2a01:111:f403:ca09::5,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 DU2PEPF00028D01.mail.protection.outlook.co...,imap.cvjm.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
1,BSBI School of Business and Innovation,berlinsbi.com,berlinsbi.com,berlinsbi.com,mx2.hc6443-94.iphmx.com,68.232.130.72,IRONPORT-SYSTEMS-INC - Cisco Systems Ironport ...,US,220 esa.hc6443-94.iphmx.com ESMTP,NaN,NaN
2,University of Labour,academy-of-labour.de,university-of-labour.de,academy-of-labour.de,academyoflabour-de01ie.mail.protection.outlook...,2a01:111:f403:ca2d::2,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 FR3PEPF00000484.mail.protection.outlook.co...,imap.academy-of-labour.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
3,Charlotte Fresenius Hochschule,hs-fresenius.de,charlotte-fresenius-uni.de,hs-fresenius.de,hsfresenius-de0e.mail.protection.outlook.com,52.101.73.153,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 DU2PEPF0001E9C1.mail.protection.outlook.co...,mail.hs-fresenius.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
4,Collegium Orientale,bistum-eichstaett.de,collegium-orientale.de,bistum-eichstaett.de,mx02.dioezesennetz.de,141.78.102.98,"ASN-TSI-IPLS - Telekom Deutschland GmbH, DE",DE,554-skibayi02.kirche-bayern.de,imap.bistum-eichstaett.de,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
...,...,...,...,...,...,...,...,...,...,...,...
5456,Zürich,NaN,stadt-zuerich.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5457,Basel,NaN,bs.ch,bs.ch,mail10.swisscom.com,138.188.176.225,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH,220 mail.swisscom.com ESMTP Service Swisscom (...,NaN,NaN
5458,Schaffhausen,NaN,stadt-schaffhausen.ch,stadt-schaffhausen.ch,miraculix2.ksd.ch,195.246.245.126,"KSD - Informatik Schaffhausen (ITSH), CH",CH,554-miraculix2.ksd.ch,NaN,NaN
5459,Bülach,NaN,buelach.ch,buelach.ch,mailprotect3.itexacloud.ch,213.221.234.85,"QUICKLINE - Quickline AG, CH",CH,220 mailprotect3.itexacloud.ch,NaN,NaN
5462,Winterthur,NaN,stadt.winterthur.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
final[(final.website_domain == final.domain) & (final.email != final.domain)]

,name,email,website_domain,domain,mx_domain,ip,owner,country,smtp_banner,imap_host,banner
2398,Duale Hochschule Baden-Württemberg Lörrach,NaN,dhbw-loerrach.de,dhbw-loerrach.de,mx3.belwue.de,2001:7c0:0:76::3,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in03.belwue.de ESMTP Postfix,imap.dhbw-loerrach.de,* OK IMAP4 ready
2399,Burg Giebichenstein Kunsthochschule Halle,NaN,burg-halle.de,burg-halle.de,burg-halle.de,212.122.56.1,"HLKOMM - HL komm Telekommunikations GmbH, DE",DE,220 ******************************************...,NaN,NaN
2400,BSP Business & Law School,NaN,businessschool-berlin.de,businessschool-berlin.de,mx-ber.mail-bz.de,62.214.51.13,"VERSATEL - 1&1 Versatel GmbH, DE",DE,220 mx-ber.mail-bz.de - NoSpamProxy ready,NaN,NaN
2401,Technische Universität Hamburg,NaN,tuhh.de,tuhh.de,smtp3.rz.tu-harburg.de,2001:638:702:20aa::205:37,DFN - Verein zur Foerderung eines Deutschen Fo...,DE,220-smtp3.rz.tu-harburg.de ESMTP Postfix (Debian),mail.tuhh.de,* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ...
2402,SRH University Campus Fürth,NaN,srh-university.de,srh-university.de,srhuniversity-de0i.mail.protection.outlook.com,2a01:111:f403:ca04::9,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 DU6PEPF0000B620.mail.protection.outlook.co...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5452,Glarus Nord,NaN,glarus-nord.ch,glarus-nord.ch,ip17.gl.ch,217.192.170.97,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH,554-mx0.gl.ch,NaN,NaN
5453,Genf,NaN,geneve.ch,geneve.ch,geneve-ch.mail.protection.outlook.com,2a01:111:f403:ca3c::,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 ZR1PEPF0000077C.mail.protection.outlook.co...,NaN,NaN
5457,Basel,NaN,bs.ch,bs.ch,mail10.swisscom.com,138.188.176.225,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH,220 mail.swisscom.com ESMTP Service Swisscom (...,NaN,NaN
5458,Schaffhausen,NaN,stadt-schaffhausen.ch,stadt-schaffhausen.ch,miraculix2.ksd.ch,195.246.245.126,"KSD - Informatik Schaffhausen (ITSH), CH",CH,554-miraculix2.ksd.ch,NaN,NaN
5459,Bülach,NaN,buelach.ch,buelach.ch,mailprotect3.itexacloud.ch,213.221.234.85,"QUICKLINE - Quickline AG, CH",CH,220 mailprotect3.itexacloud.ch,NaN,NaN

In [19]:
final[final["name"].duplicated(keep=False)]

,name,email,website_domain,domain,mx_domain,ip,owner,country,smtp_banner,imap_host,banner
239,Pädagogische Hochschule Freiburg,unifr.ch,hepfr.ch,unifr.ch,mxa-00626501.gslb.pphosted.com,66.159.233.182,"PROOFPOINT-ASN-EU - Proofpoint, Inc., US",US,"220 mx07-00626501.pphosted.com ESMTP Wed, 10 J...",NaN,NaN
434,Krankenhaus Barmherzige Brüder,barmherzige-regensburg.de,barmherzige-regensburg.de,barmherzige-regensburg.de,mx04.hornetsecurity.com,94.100.136.7,"SSERV-AS - kyberio GmbH, DE",DE,220 mx-gate44-hz2.hornetsecurity.com,NaN,NaN
458,Martin-Luther-Krankenhaus,klinikum-bochum.de,martin-luther-krankenhaus-bo.de,klinikum-bochum.de,mx02.hornetsecurity.com,94.100.136.8,"SSERV-AS - kyberio GmbH, DE",DE,220 mx-gate45-hz2.hornetsecurity.com,NaN,NaN
614,Martini-Klinik,uke.de,martini-klinik.de,uke.de,iplexus2.uke.uni-hamburg.de,134.100.102.33,DFN - Verein zur Foerderung eines Deutschen Fo...,DE,554-iplexus.uke.uni-hamburg.de,imap.uke.de,* OK The Microsoft Exchange IMAP4 service is r...
952,Bundespatentgericht,bpatg.bund.de,bundespatentgericht.de,bpatg.bund.de,mx1.bund.de,77.87.224.131,BSI-AS - Bundesministerium des Innern und fuer...,DE,220 mx1.bund.de ESMTP,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5453,Genf,NaN,geneve.ch,geneve.ch,geneve-ch.mail.protection.outlook.com,2a01:111:f403:ca3c::,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 ZR1PEPF0000077C.mail.protection.outlook.co...,NaN,NaN
5454,Genf,NaN,geneve.ch,geneve.ch,geneve-ch.mail.protection.outlook.com,52.101.187.1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 ZR1PEPF0000077C.mail.protection.outlook.co...,NaN,NaN
5459,Bülach,NaN,buelach.ch,buelach.ch,mailprotect3.itexacloud.ch,213.221.234.85,"QUICKLINE - Quickline AG, CH",CH,220 mailprotect3.itexacloud.ch,NaN,NaN
5460,Bülach,NaN,buelach.ch,buelach.ch,buelach-ch.mail.protection.outlook.com,2a01:111:f403:ca04::4,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 AMS1EPF0000004A.mail.protection.outlook.co...,NaN,NaN
5461,Bülach,NaN,buelach.ch,buelach.ch,buelach-ch.mail.protection.outlook.com,52.101.73.1,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,US,220 AMS1EPF0000004A.mail.protection.outlook.co...,NaN,NaN

In [15]:
domain_email[domain_email.email.isna()].merge(temp, left_on="email", right_on="domain", how="left")

,name,email,website_domain,domain_x,mx_domain_x,ip_x,owner_x,country_x,smtp_banner_x,imap_host_x,banner_x,domain_y,mx_domain_y,ip_y,owner_y,country_y,smtp_banner_y,imap_host_y,banner_y
0,Duale Hochschule Baden-Württemberg Lörrach,NaN,dhbw-loerrach.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Burg Giebichenstein Kunsthochschule Halle,NaN,burg-halle.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BSP Business & Law School,NaN,businessschool-berlin.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Technische Universität Hamburg,NaN,tuhh.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SRH University Campus Fürth,NaN,srh-university.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2603,Zürich,NaN,stadt-zuerich.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2604,Basel,NaN,bs.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2605,Schaffhausen,NaN,stadt-schaffhausen.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2606,Bülach,NaN,buelach.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2607,Winterthur,NaN,stadt.winterthur.ch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
domain_mx = pd.merge(domain[["name", "website_domain"]], mx, on="website_domain")
domain_mx

,name,website_domain,mx_domain,error
0,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx2.belwue.de,NaN
1,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx3.belwue.de,NaN
2,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx4.belwue.de,NaN
3,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx1.belwue.de,NaN
4,Burg Giebichenstein Kunsthochschule Halle,burg-halle.de,burg-halle.de,NaN
...,...,...,...,...
8938,Schaffhausen,stadt-schaffhausen.ch,miraculix2.ksd.ch,NaN
8939,Schaffhausen,stadt-schaffhausen.ch,miraculix1.ksd.ch,NaN
8940,Bülach,buelach.ch,buelach-ch.mail.protection.outlook.com,NaN
8941,Bülach,buelach.ch,mailprotect3.itexacloud.ch,NaN
8942,Winterthur,stadt.winterthur.ch,NaN,The DNS response does not contain an answer to...

In [10]:
import re

MX_PROVIDER_RULES = [
    (re.compile(r"\b(?:mx\d*\.)?hornetsecurity\."), "Hornetsecurity"),
    (re.compile(r"\bantispameurope\."), "Hornetsecurity"),  # ehemalige Marke
    (re.compile(r"\boutlook\.com$"), "Microsoft 365"),
    (re.compile(r"\bprotection\.outlook\.com$"), "Microsoft 365"),
    (re.compile(r"\bionos\."), "IONOS"),
    (re.compile(r"\bbelwue\."), "BelWü"),
    (re.compile(r"\bkvnb\."), "KVNB"),
]

def identify_provider(mx_domain: str) -> str | None:
    mx_domain = mx_domain.lower()

    for pattern, provider in MX_PROVIDER_RULES:
        if pattern.search(mx_domain):
            return provider

    return None

In [13]:
domain_mx["mx_provider"] = (
    domain_mx["mx_domain"]
    .fillna("")
    .apply(identify_provider)
)
domain_mx.drop_duplicates(subset="name", inplace=True)

In [14]:
domain_mx

,name,website_domain,mx_domain,error,mx_provider
0,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx2.belwue.de,NaN,BelWü
4,Burg Giebichenstein Kunsthochschule Halle,burg-halle.de,burg-halle.de,NaN,NaN
5,BSP Business & Law School,businessschool-berlin.de,mx-hh.mail-bz.de,NaN,NaN
7,CVJM-Hochschule,cvjm-hochschule.de,mx1.serve-me.de,NaN,NaN
9,Technische Universität Hamburg,tuhh.de,smtp3.rz.tu-harburg.de,NaN,NaN
...,...,...,...,...,...
8934,Basel,bs.ch,mail.swisscom.com,NaN,NaN
8937,Lausanne,lausanne.ch,mxvdl.lausanne.ch,NaN,NaN
8938,Schaffhausen,stadt-schaffhausen.ch,miraculix2.ksd.ch,NaN,NaN
8940,Bülach,buelach.ch,buelach-ch.mail.protection.outlook.com,NaN,Microsoft 365
8942,Winterthur,stadt.winterthur.ch,NaN,The DNS response does not contain an answer to...,NaN

In [27]:
domain_ip = pd.merge(domain_mx,  ip[["mx_domain","ip"]], on="mx_domain")
domain_asn = pd.merge(domain_ip, asn[["ip", "owner", "country"]], on="ip", how="left")
domain_asn = domain_asn.drop(columns=["error", "ip"]).drop_duplicates(subset="name")
domain_asn

,name,website_domain,mx_domain,mx_provider,owner,country
0,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx2.belwue.de,BelWü,"BELWUE - Universitaet Stuttgart, DE",DE
2,Burg Giebichenstein Kunsthochschule Halle,burg-halle.de,burg-halle.de,NaN,"HLKOMM - HL komm Telekommunikations GmbH, DE",DE
3,BSP Business & Law School,businessschool-berlin.de,mx-hh.mail-bz.de,NaN,"VERSATEL - 1&1 Versatel GmbH, DE",DE
4,CVJM-Hochschule,cvjm-hochschule.de,mx1.serve-me.de,NaN,"HETZNER-AS - Hetzner Online GmbH, DE",DE
5,Technische Universität Hamburg,tuhh.de,smtp3.rz.tu-harburg.de,NaN,DFN - Verein zur Foerderung eines Deutschen Fo...,DE
...,...,...,...,...,...,...
8456,Basel,bs.ch,mail.swisscom.com,NaN,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH
8458,Lausanne,lausanne.ch,mxvdl.lausanne.ch,NaN,SIL-CITYCABLE-AS - Services Industriels de Lau...,CH
8459,Schaffhausen,stadt-schaffhausen.ch,miraculix2.ksd.ch,NaN,"KSD - Informatik Schaffhausen (ITSH), CH",CH
8460,Bülach,buelach.ch,buelach-ch.mail.protection.outlook.com,Microsoft 365,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB
8468,Winterthur,stadt.winterthur.ch,NaN,NaN,NaN,NaN

In [30]:
domain_smtp = pd.merge(domain_asn, smtp[["mx_domain", "smtp_banner"]], on="mx_domain")
domain_smtp

,name,website_domain,mx_domain,mx_provider,owner,country,smtp_banner
0,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx2.belwue.de,BelWü,"BELWUE - Universitaet Stuttgart, DE",DE,220 mail-in02.belwue.de ESMTP Postfix
1,Burg Giebichenstein Kunsthochschule Halle,burg-halle.de,burg-halle.de,NaN,"HLKOMM - HL komm Telekommunikations GmbH, DE",DE,220 ******************************************...
2,BSP Business & Law School,businessschool-berlin.de,mx-hh.mail-bz.de,NaN,"VERSATEL - 1&1 Versatel GmbH, DE",DE,220 mx-hh.mail-bz.de - NoSpamProxy ready
3,CVJM-Hochschule,cvjm-hochschule.de,mx1.serve-me.de,NaN,"HETZNER-AS - Hetzner Online GmbH, DE",DE,220 mx1.serve-me.de ESMTP
4,Technische Universität Hamburg,tuhh.de,smtp3.rz.tu-harburg.de,NaN,DFN - Verein zur Foerderung eines Deutschen Fo...,DE,220-smtp3.rz.tu-harburg.de ESMTP Postfix (Debian)
...,...,...,...,...,...,...,...
4985,Basel,bs.ch,mail.swisscom.com,NaN,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH,220 mail.swisscom.com ESMTP Service Swisscom (...
4986,Lausanne,lausanne.ch,mxvdl.lausanne.ch,NaN,SIL-CITYCABLE-AS - Services Industriels de Lau...,CH,"220 lsamgwp03.lausanne.ch ESMTP Smtpd; Mon, 8 ..."
4987,Schaffhausen,stadt-schaffhausen.ch,miraculix2.ksd.ch,NaN,"KSD - Informatik Schaffhausen (ITSH), CH",CH,554-miraculix2.ksd.ch
4988,Bülach,buelach.ch,buelach-ch.mail.protection.outlook.com,Microsoft 365,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,220 AMS1EPF0000003F.mail.protection.outlook.co...
4989,Winterthur,stadt.winterthur.ch,NaN,NaN,NaN,NaN,NaN

In [31]:
from collections import Counter
domain_mx = pd.merge(domain[["name", "website_domain"]], mx, on="website_domain")

def count_mx_parts(df):
    counter = Counter()

    for mx in df["smtp_banner"].dropna():
        parts = mx.split(".")
        counter.update(parts)

    return (
        pd.DataFrame(
            counter.items(),
            columns=["part", "count"]
        )
        .sort_values("count", ascending=False)
        .reset_index(drop=True)
    )

count_mx_parts(domain_smtp)

                                                  part  count
0                                     de ESMTP Postfix    914
1                                             220 mail    478
2                                                 mail    375
3                                              outlook    351
4                                           protection    350
...                                                ...    ...
2862                                     220 lsamgwp03      1
2863                                         220-c2281      1
2864                                             hs-nb      1
2865  com ESMTP 41be03b00d2f7-c85df0e5380si25752674a12      1
2866                                       277 - gsmtp      1

[2867 rows x 2 columns]

In [35]:
import re

BANNER_RULES = [
    # Microsoft / Outlook / Exchange Online
    (re.compile(r"outlook|protection\.outlook|mail\.protection\.outlook"), "Microsoft 365"),

    # Hornetsecurity / Antispameurope
    (re.compile(r"hornetsecurity|antispameurope"), "Hornetsecurity"),

    # Postfix (MTA, self-hosted)
    (re.compile(r"\bpostfix\b"), "Self Hosted"),

    # KVNB / KVNBW (unscharf, regional IT)
    (re.compile(r"kvnbw|kvnb"), "KVNBW"),

    # # Generic SMTP / Relay Hinweise
    # (re.compile(r"\besmtp\b|smtp relay|mail relay"), "Generischer SMTP Relay"),

    # Sophos Mail Gateway
    (re.compile(r"sophos|mailgateway.*sophos"), "Sophos Mail Gateway"),

    # # Hydra (unspezifisch, oft Tool/Appliance)
    # (re.compile(r"\bhydra\b"), "Hydra (unsicher: Tool oder interne Appliance)"),

    # Mimecast (sehr häufig Enterprise Mail Security)
    (re.compile(r"mimecast"), "Mimecast Email Security"),

    # Your-server (typisch Hosting / VPS / Hetzner-ähnliche Umgebungen)
    (re.compile(r"your[- ]?server"), "Hetzner"),
]


def identify_provider(mx_domain: str) -> str | None:
    mx_domain = mx_domain.lower()

    for pattern, provider in BANNER_RULES:
        if pattern.search(mx_domain):
            return provider

    return None

domain_smtp["smtp_provider"] = (
    domain_smtp["smtp_banner"]
    .fillna("")
    .apply(identify_provider)
)
domain_smtp.drop(columns="smtp_banner")#.drop_duplicates(subset="name", inplace=True)

,name,website_domain,mx_domain,mx_provider,owner,country,smtp_provider
0,Duale Hochschule Baden-Württemberg Lörrach,dhbw-loerrach.de,mx2.belwue.de,BelWü,"BELWUE - Universitaet Stuttgart, DE",DE,Self Hosted
1,Burg Giebichenstein Kunsthochschule Halle,burg-halle.de,burg-halle.de,NaN,"HLKOMM - HL komm Telekommunikations GmbH, DE",DE,NaN
2,BSP Business & Law School,businessschool-berlin.de,mx-hh.mail-bz.de,NaN,"VERSATEL - 1&1 Versatel GmbH, DE",DE,NaN
3,CVJM-Hochschule,cvjm-hochschule.de,mx1.serve-me.de,NaN,"HETZNER-AS - Hetzner Online GmbH, DE",DE,NaN
4,Technische Universität Hamburg,tuhh.de,smtp3.rz.tu-harburg.de,NaN,DFN - Verein zur Foerderung eines Deutschen Fo...,DE,Self Hosted
...,...,...,...,...,...,...,...
4985,Basel,bs.ch,mail.swisscom.com,NaN,"SWISSCOM - Swisscom (Schweiz) AG, CH",CH,NaN
4986,Lausanne,lausanne.ch,mxvdl.lausanne.ch,NaN,SIL-CITYCABLE-AS - Services Industriels de Lau...,CH,NaN
4987,Schaffhausen,stadt-schaffhausen.ch,miraculix2.ksd.ch,NaN,"KSD - Informatik Schaffhausen (ITSH), CH",CH,NaN
4988,Bülach,buelach.ch,buelach-ch.mail.protection.outlook.com,Microsoft 365,MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpor...,GB,Microsoft 365
4989,Winterthur,stadt.winterthur.ch,NaN,NaN,NaN,NaN,NaN

In [51]:
def coverage_table(df):
    total = len(df)

    mx = df["mx_provider"].notna()
    owner = df["owner"].notna()
    smtp = df["smtp_provider"].notna()

    mx_only = mx.sum()

    mx_or_owner = mx | (~mx & owner)
    owner_added = mx_or_owner.sum()

    mx_owner_or_smtp = mx_or_owner | (~mx_or_owner & smtp)
    smtp_added = mx_owner_or_smtp.sum()

    print()
    print(f"MX only: {mx.mean() * 100:.3f}%")
    print(f"ASN added: {(owner_added - mx_only) / total * 100:.3f}%")
    print(f"SMTP added: {(smtp_added - owner_added) / total * 100:.3f}%")
    print(f"Final coverage: {smtp_added / total * 100:.3f}%")

coverage_table(domain_smtp)

MX only: 11.663%
ASN added: 72.445%
SMTP added: 0.000%
Final coverage: 84.108%

In [50]:
len(domain_smtp[(domain_smtp["mx_provider"].notna() | domain_smtp["owner"].notna() | domain_smtp["smtp_provider"].notna())]) / len(domain_smtp)

0.8410821643286573

In [11]:
class Test:
    pass

test = Test()

print(type(test).__name__)

Test

In [4]:
import pandas as pd
df = pd.read_csv("/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/mail_server_scan_results.csv")
df

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,...,latitude,timestamp,email_mail_server,email_mail_port,email_mail_protocol,email_mail_banner,website_domain_mail_server,website_domain_mail_port,website_domain_mail_protocol,website_domain_mail_banner
0,f604925d-96f6-4313-843c-f92da890e844,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,Deutschland,http://www.cvjm-hochschule.de/,cvjm.de,university,cvjm-hochschule.de,...,51.303670,2026-05-31 20:08:03.862087,mail.cvjm.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,NaN,NaN,NaN,NaN
1,fec9310f-4548-448c-83c6-b9f2be1e42bd,http://www.wikidata.org/entity/Q107440148,BSBI School of Business and Innovation,Berlin,Berlin,Deutschland,https://www.berlinsbi.com/,berlinsbi.com,university,berlinsbi.com,...,NaN,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,70ea6341-72c6-4496-bbe7-a1e1273cc7dd,http://www.wikidata.org/entity/Q110489587,University of Labour,Frankfurt am Main,Hessen,Deutschland,https://www.university-of-labour.de/,academy-of-labour.de,university,university-of-labour.de,...,50.130408,2026-05-31 20:08:03.862087,imap.academy-of-labour.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,mail.university-of-labour.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
3,50c0ecbf-a773-4804-bd6e-69d2e85a717c,http://www.wikidata.org/entity/Q110624130,Charlotte Fresenius Hochschule,München,Hessen,Deutschland,https://www.charlotte-fresenius-uni.de/,hs-fresenius.de,university,charlotte-fresenius-uni.de,...,NaN,2026-05-31 20:08:03.862087,mail.hs-fresenius.de,587.0,SMTP-STARTTLS,220 srv-maildovecotdirector01 Dovecot (Ubuntu)...,NaN,NaN,NaN,NaN
4,c15f7a86-68d6-4ea2-a88c-a3390c8244b3,http://www.wikidata.org/entity/Q1109275,Collegium Orientale,NaN,NaN,Deutschland,http://www.collegium-orientale.de,bistum-eichstaett.de,university,collegium-orientale.de,...,48.890600,2026-05-31 20:08:03.862087,mail.bistum-eichstaett.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,webmail.collegium-orientale.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,55438d6a-e7fa-4407-8bd2-48dcbc17dbc9,http://www.wikidata.org/entity/Q69734,Bassersdorf,Bassersdorf,NaN,Schweiz,https://www.bassersdorf.ch,bassersdorf.ch,city,bassersdorf.ch,...,47.443056,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2411,70cec793-a7c4-455c-b6b5-67b7f267f74e,http://www.wikidata.org/entity/Q69752,Rüti,Rüti,NaN,Schweiz,https://www.rueti.ch,rueti.ch,city,rueti.ch,...,47.261389,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2412,c165c74b-29f7-40eb-9c7f-943091fa8433,http://www.wikidata.org/entity/Q69783,Münsingen,Münsingen,NaN,Schweiz,https://www.muensingen.ch,muensingen.ch,city,muensingen.ch,...,46.872980,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2413,fb158c02-0df9-4ad8-816c-6f77c0fabecc,http://www.wikidata.org/entity/Q70,Bern,Bern,NaN,Schweiz,https://www.bern.ch/it,bern.ch,city,bern.ch,...,46.947980,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2414,b09f2231-55c6-43f7-8939-d3633e435593,http://www.wikidata.org/entity/Q807,Lausanne,Lausanne,NaN,Schweiz,https://www.lausanne.ch/,lausanne.ch,city,lausanne.ch,...,46.533333,2026-05-31 20:08:03.862087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df[df['email_mail_protocol'] == "IMAP"]

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,...,latitude,timestamp,email_mail_server,email_mail_port,email_mail_protocol,email_mail_banner,website_domain_mail_server,website_domain_mail_port,website_domain_mail_protocol,website_domain_mail_banner
0,f604925d-96f6-4313-843c-f92da890e844,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,Deutschland,http://www.cvjm-hochschule.de/,cvjm.de,university,cvjm-hochschule.de,...,51.303670,2026-05-31 20:08:03.862087,mail.cvjm.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,NaN,NaN,NaN,NaN
2,70ea6341-72c6-4496-bbe7-a1e1273cc7dd,http://www.wikidata.org/entity/Q110489587,University of Labour,Frankfurt am Main,Hessen,Deutschland,https://www.university-of-labour.de/,academy-of-labour.de,university,university-of-labour.de,...,50.130408,2026-05-31 20:08:03.862087,imap.academy-of-labour.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,mail.university-of-labour.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
4,c15f7a86-68d6-4ea2-a88c-a3390c8244b3,http://www.wikidata.org/entity/Q1109275,Collegium Orientale,NaN,NaN,Deutschland,http://www.collegium-orientale.de,bistum-eichstaett.de,university,collegium-orientale.de,...,48.890600,2026-05-31 20:08:03.862087,mail.bistum-eichstaett.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,webmail.collegium-orientale.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
5,2d4b3edf-a951-4f21-ad46-a0c8602e874c,http://www.wikidata.org/entity/Q1109299,Collegium Willibaldinum,Eichstätt,Bayern,Deutschland,https://www.priesterseminar-eichstaett.de/star...,bistum-eichstaett.de,university,priesterseminar-eichstaett.de,...,48.890658,2026-05-31 20:08:03.862087,mail.bistum-eichstaett.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,NaN,NaN,NaN,NaN
6,fa4c1304-92be-4ebc-b247-136e38e94cad,http://www.wikidata.org/entity/Q113633597,Universität Koblenz,Koblenz,Rheinland-Pfalz,Deutschland,https://www.uni-koblenz.de/de,uni-koblenz.de,university,uni-koblenz.de,...,50.363611,2026-05-31 20:08:03.862087,imap.uni-koblenz.de,143.0,IMAP,* OK IMAP4 ready,smtp.uni-koblenz.de,25.0,SMTP,220 mailproxy.uni-koblenz.de ESMTP Postfix (Ub...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319,ea79a8b4-1f0a-4d65-a0a4-c0bfd97abef8,http://www.wikidata.org/entity/Q7033,Nordhausen,Nordhausen,Thüringen,Deutschland,https://www.nordhausen.de/,nordhausen.de,city,nordhausen.de,...,51.505000,2026-05-31 20:08:03.862087,webmail.nordhausen.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,mail.nordhausen.de,587.0,SMTP-STARTTLS,220 vwp0542.webpack.hosteurope.de ESMTP Host E...
2348,607b62b9-fad7-4159-a880-f2d0013e5ab6,http://www.wikidata.org/entity/Q8240,Stadt Wehlen,Stadt Wehlen,Sachsen,Deutschland,https://www.wehlen-online.de/,wehlen-online.de,city,wehlen-online.de,...,50.956944,2026-05-31 20:08:03.862087,webmail.wehlen-online.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,imap.wehlen-online.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
2353,7e6534ed-1225-452c-af7a-01a268f8a8e7,http://www.wikidata.org/entity/Q8714,Großenhain,Großenhain,Sachsen,Deutschland,https://www.grossenhain.de/,grossenhain.de,city,grossenhain.de,...,51.291944,2026-05-31 20:08:03.862087,mail.grossenhain.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ...,imap.grossenhain.de,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ...
2367,6f07fd32-4ac5-4804-a443-bff9ffbe4cbf,http://www.wikidata.org/entity/Q259214,Rust,Rust,NaN,Österreich,https://www.freistadt-rust.at/,freistadt-rust.at,city,freistadt-rust.at,...,47.800833,2026-05-31 20:08:03.862087,mail.freistadt-rust.at,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...,mail.freistadt-rust.at,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFER...
2380,5c4fb435-5548-4850-a114-ab407ed5bc28,http://www.wikidata.org/entity/Q660749,Nickelsdorf,Nickelsdorf,NaN,Österreich,http://www.nickelsdorf.at/,nickelsdorf.at,city,nickelsdorf.at,...,47.940555,2026-05-31 20:08:03.862087,mail.nickelsdorf.at,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NA...,mail.nickelsdorf.at,143.0,IMAP,* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NA...

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(
        "D:\\Projekte\\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\\scanner\\database\\raw_data.db"
    )

df = pd.read_sql_query("SELECT * FROM bronze_table", conn)

import json

with open(r"D:\Projekte\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\scanner\cache_dump.json") as f:
    cache_dump = json.load(f)
cache_dump

df

DatabaseError: Execution failed on sql 'SELECT * FROM bronze_table': no such table: bronze_table

In [2]:
import pandas as pd
import sqlite3

conn = sqlite3.connect(
        "/home/julian/Projects/S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool/scanner/database/raw_data.db"
    )

df = pd.read_sql_query("SELECT * FROM bronze_table", conn)
df

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,longitude,latitude,timestamp
0,8ea3ab84-6409-4a43-b496-039136f960c4,http://www.wikidata.org/entity/Q1001338,Duale Hochschule Baden-Württemberg Lörrach,Lörrach,Baden-Württemberg,Deutschland,http://www.dhbw-loerrach.de/,NaN,university,dhbw-loerrach.de,7.677240,47.617330,2026-05-31 20:08:03.862087
1,53234a52-8bd8-46ba-8c52-493cd32f82e8,http://www.wikidata.org/entity/Q1011953,Burg Giebichenstein Kunsthochschule Halle,Halle (Saale),Sachsen-Anhalt,Deutschland,https://www.burg-halle.de/,NaN,university,burg-halle.de,11.954900,51.502700,2026-05-31 20:08:03.862087
2,3d1a5654-c62d-4274-a07f-8c4c65334c76,http://www.wikidata.org/entity/Q1017599,BSP Business & Law School,Berlin,Berlin,Deutschland,https://www.businessschool-berlin.de/,NaN,university,businessschool-berlin.de,13.054074,52.406958,2026-05-31 20:08:03.862087
3,f604925d-96f6-4313-843c-f92da890e844,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,Deutschland,http://www.cvjm-hochschule.de/,cvjm.de,university,cvjm-hochschule.de,9.414510,51.303670,2026-05-31 20:08:03.862087
4,215a8e0a-2b57-4b2a-9983-004788e8726c,http://www.wikidata.org/entity/Q1060,Technische Universität Hamburg,Hamburg,Hamburg,Deutschland,https://www.tuhh.de/,NaN,university,tuhh.de,9.969506,53.460958,2026-05-31 20:08:03.862087
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5018,da919250-2571-4130-8171-749a1294d6d9,http://www.wikidata.org/entity/Q78,Basel,Basel,NaN,Schweiz,https://www.bs.ch/,NaN,city,bs.ch,7.590555,47.560556,2026-05-31 20:08:03.862087
5019,b09f2231-55c6-43f7-8939-d3633e435593,http://www.wikidata.org/entity/Q807,Lausanne,Lausanne,NaN,Schweiz,https://www.lausanne.ch/,lausanne.ch,city,lausanne.ch,6.633333,46.533333,2026-05-31 20:08:03.862087
5020,171d6745-0367-456b-9185-85a729b13aff,http://www.wikidata.org/entity/Q9009,Schaffhausen,Schaffhausen,NaN,Schweiz,https://www.stadt-schaffhausen.ch/,NaN,city,stadt-schaffhausen.ch,8.633860,47.696530,2026-05-31 20:08:03.862087
5021,7f0bc9e7-86a8-4835-a0a8-861943a80979,http://www.wikidata.org/entity/Q9093,Bülach,Bülach,NaN,Schweiz,https://www.buelach.ch,NaN,city,buelach.ch,8.542222,47.518889,2026-05-31 20:08:03.862087
5022,ba94d145-8bb3-4562-b77d-a84ca08babff,http://www.wikidata.org/entity/Q9125,Winterthur,Winterthur,NaN,Schweiz,https://stadt.winterthur.ch,NaN,city,stadt.winterthur.ch,8.726710,47.499200,2026-05-31 20:08:03.862087

In [2]:
df["mx"] = None
df["smtp"] = None
df["asn"] = None
df["country"] = None

for index, row in df.iterrows():
    domain = cache_dump.get(row["website_domain"])

    if not domain or "mx" not in domain:
        continue

    df.at[index, "mx"] = domain["mx"]

    smtps = []
    ips = []
    for mx in domain["mx"]:
        if mx and mx in cache_dump:
            if "smtp" in cache_dump[mx]:
                smtps.append(cache_dump[mx]["smtp"])

            if "ip" in cache_dump[mx]:
                ips.extend(cache_dump[mx]["ip"])

    if smtps:
        df.at[index, "smtp"] = smtps

    asns = []
    countries = []
    for ip in ips:
        if ip in cache_dump:
            if "asn" in cache_dump[ip]:
                asns.append(cache_dump[ip]["asn"]["owner"])
                countries.append(cache_dump[ip]["asn"]["country"])

    if asns:
        df.at[index, "asn"] = asns
    if countries:
        df.at[index, "country"] = countries
df

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,longitude,latitude,timestamp,mx,smtp,asn
0,b8381380-f672-4c15-a743-fe0ce1509ffe,http://www.wikidata.org/entity/Q1001338,Duale Hochschule Baden-Württemberg Lörrach,Lörrach,Baden-Württemberg,"[DE, DE, DE, DE, DE, DE, DE, DE, DE, DE, DE, DE]",http://www.dhbw-loerrach.de/,NaN,university,dhbw-loerrach.de,7.677240,47.617330,2026-05-08 15:30:11.685839,"[mx4.belwue.de, mx2.belwue.de, mx1.belwue.de, ...","[220 mail-in04.belwue.de ESMTP Postfix, 220 ma...","[BELWUE BelWue-Koordination, DE, BELWUE BelWue..."
1,a32648ed-7586-4ed4-9946-80adb13ccedb,http://www.wikidata.org/entity/Q1011953,Burg Giebichenstein Kunsthochschule Halle,Halle (Saale),Sachsen-Anhalt,[DE],https://www.burg-halle.de/,NaN,university,burg-halle.de,11.954900,51.502700,2026-05-08 15:30:11.685839,[burg-halle.de],[220 *****************************************...,"[HLKOMM 04107 Leipzig, DE]"
2,cf712634-996a-4f39-8990-a56f8411582e,http://www.wikidata.org/entity/Q1017599,BSP Business & Law School,Berlin,Berlin,"[DE, DE]",https://www.businessschool-berlin.de/,NaN,university,businessschool-berlin.de,13.054074,52.406958,2026-05-08 15:30:11.685839,"[mx-hh.mail-bz.de, mx-ber.mail-bz.de]","[220 mx-hh.mail-bz.de - NoSpamProxy ready, 220...","[VERSATEL, DE, VERSATEL, DE]"
3,bef4aea6-6ff7-4ab9-a562-23c24309d4a0,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,"[DE, DE]",http://www.cvjm-hochschule.de/,NaN,university,cvjm-hochschule.de,9.414510,51.303670,2026-05-08 15:30:11.685839,"[mx2.serve-me.de, mx1.serve-me.de]","[220 mx2.serve-me.de ESMTP, 220 mx1.serve-me.d...","[HETZNER-AS, DE, HETZNER-AS, DE]"
4,76eb7cc0-0321-43a4-a8ee-522dc3172a46,http://www.wikidata.org/entity/Q1060,Technische Universität Hamburg,Hamburg,Hamburg,"[DE, DE, DE, DE, DE, DE]",https://www.tuhh.de/,NaN,university,tuhh.de,9.969506,53.460958,2026-05-08 15:30:11.685839,"[smtp3.rz.tu-harburg.de, smtp4.rz.tu-harburg.d...",[220-smtp3.rz.tu-harburg.de ESMTP Postfix (Deb...,[DFN Verein zur Foerderung eines Deutschen For...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,db56a6e0-a38c-4745-aec6-4e2397a0dc43,http://www.wikidata.org/entity/Q78,Basel,Basel,NaN,"[CH, CH, CH, CH]",https://www.bs.ch/,NaN,city,bs.ch,7.590555,47.560556,2026-05-08 15:30:11.685839,"[mail.swisscom.com, mail20.swisscom.com, mail1...",[220 mail.swisscom.com ESMTP Service Swisscom ...,"[SWISSCOM Swisscom Switzerland Ltd, CH, SWISSC..."
5008,41ade22b-becb-4763-b1b0-af2a6b472c78,http://www.wikidata.org/entity/Q807,Lausanne,Lausanne,NaN,[CH],https://www.lausanne.ch/,NaN,city,lausanne.ch,6.633333,46.533333,2026-05-08 15:30:11.685839,[mxvdl.lausanne.ch],"[220 lsamgwp03.lausanne.ch ESMTP Smtpd; Mon, 1...","[SIL-CITYCABLE-AS, CH]"
5009,83f3c00c-5800-489f-8af9-0e6798f22610,http://www.wikidata.org/entity/Q9009,Schaffhausen,Schaffhausen,NaN,"[CH, CH]",https://www.stadt-schaffhausen.ch/,NaN,city,stadt-schaffhausen.ch,8.633860,47.696530,2026-05-08 15:30:11.685839,"[miraculix2.ksd.ch, miraculix1.ksd.ch]","[554-miraculix2.ksd.ch, 554-miraculix1.ksd.ch]","[KSD, CH, KSD, CH]"
5010,aca98be5-3763-4199-9b48-a633e1a03434,http://www.wikidata.org/entity/Q9093,Bülach,Bülach,NaN,"[GB, US, US, GB, US, GB, GB, US, CH]",https://www.buelach.ch,NaN,city,buelach.ch,8.542222,47.518889,2026-05-08 15:30:11.685839,"[buelach-ch.mail.protection.outlook.com, mailp...",[220 DB1PEPF000509ED.mail.protection.outlook.c...,[MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpo...
5011,a54a81f3-7eac-4eeb-a58a-481d6e7a2e5e,http://www.wikidata.org/entity/Q9125,Winterthur,Winterthur,NaN,None,https://stadt.winterthur.ch,NaN,city,stadt.winterthur.ch,8.726710,47.499200,2026-05-08 15:30:11.685839,None,None,None

In [3]:
def clean_list(items):
    result = []

    for item in items:
        # Verschachtelte Listen rekursiv auflösen
        if isinstance(item, list):
            result.extend(clean_list(item))
            continue

        # None entfernen
        if item is None:
            continue

        # Strings trimmen
        if isinstance(item, str):
            item = item.strip()

            # Leere Strings entfernen
            if item == "":
                continue

        result.append(item)

    return result

In [4]:
import re

def extract_smtp_tech(banner):
    """
    Extracts common SMTP technologies from a banner string.
    Returns a list of detected technologies.
    """

    if not banner or not isinstance(banner, str):
        return []

    banner_lower = banner.lower()

    tech_map = {
        "postfix": r"postfix",
        "exim": r"exim",
        "sendmail": r"sendmail",
        "exchange": r"microsoft exchange|exchange",
        "microsoft_smtp": r"microsoft esmtp|microsoft smtp",
        "dovecot": r"dovecot",
        "qmail": r"qmail",
        "openssh_smtp": r"openssh",
        "openssl": r"openssl",
        "starttls": r"starttls",
        "tls": r"\btls\b|ssl",
        "esmtp": r"\besmtp\b",
    }

    detected = []

    for tech, pattern in tech_map.items():
        if re.search(pattern, banner_lower):
            detected.append(tech)

    return detected

df["smtp_software"] = df["smtp"].apply(
    lambda banners: [
        extract_smtp_tech(banner)
        for banner in banners
    ] if isinstance(banners, list) else []
)
df["smtp_software"] = df["smtp_software"].apply(clean_list)
df["smtp_software"] = df["smtp_software"].apply(
    lambda x: list(set(x)) if isinstance(x, list) else x
)
df["country"] = df["country"].apply(
    lambda x: list(set(x)) if isinstance(x, list) else x
)
df["asn"] = df["asn"].apply(
    lambda x: list(set(x)) if isinstance(x, list) else x
)

def split_asn(asn_list):

    if not isinstance(asn_list, list):
        return [], []

    providers = []
    countries = []

    for item in asn_list:

        if not isinstance(item, str):
            continue

        parts = item.split(",")

        provider = parts[0].strip()
        country = parts[-1].strip() if len(parts) > 1 else None

        providers.append(provider)

        if country:
            countries.append(country)

    # unique + Reihenfolge behalten
    providers = list(dict.fromkeys(providers))
    countries = list(dict.fromkeys(countries))

    return providers, country

df[["provider", "provider_country"]] = df["asn"].apply(
    lambda x: pd.Series(split_asn(x))
)
def determine_sovereignty(countries):

    if not isinstance(countries, list) or not countries:
        return "medium"

    unique = set(countries)

    if "US" in unique:
        return "low"

    if unique == {"DE"}:
        return "high"

    return "medium"
df["sovereignty_level"] = df["country"].apply(determine_sovereignty)
def determine_provider_type(providers):

    if not isinstance(providers, list):
        return "self_hosted"

    hyperscaler_keywords = [
        "google",
        "microsoft",
        "amazon",
    ]

    for provider in providers:

        if not isinstance(provider, str):
            continue

        provider_lower = provider.lower()

        if any(keyword in provider_lower for keyword in hyperscaler_keywords):
            return "hyperscaler"

    return "self-hosted"

df["provider_type"] = df["provider"].apply(determine_provider_type)
df

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,...,latitude,timestamp,mx,smtp,asn,smtp_software,provider,provider_country,sovereignty_level,provider_type
0,b8381380-f672-4c15-a743-fe0ce1509ffe,http://www.wikidata.org/entity/Q1001338,Duale Hochschule Baden-Württemberg Lörrach,Lörrach,Baden-Württemberg,[DE],http://www.dhbw-loerrach.de/,NaN,university,dhbw-loerrach.de,...,47.617330,2026-05-08 15:30:11.685839,"[mx4.belwue.de, mx2.belwue.de, mx1.belwue.de, ...","[220 mail-in04.belwue.de ESMTP Postfix, 220 ma...","[BELWUE BelWue-Koordination, DE]","[postfix, esmtp]",[BELWUE BelWue-Koordination],DE,high,self-hosted
1,a32648ed-7586-4ed4-9946-80adb13ccedb,http://www.wikidata.org/entity/Q1011953,Burg Giebichenstein Kunsthochschule Halle,Halle (Saale),Sachsen-Anhalt,[DE],https://www.burg-halle.de/,NaN,university,burg-halle.de,...,51.502700,2026-05-08 15:30:11.685839,[burg-halle.de],[220 *****************************************...,"[HLKOMM 04107 Leipzig, DE]",[],[HLKOMM 04107 Leipzig],DE,high,self-hosted
2,cf712634-996a-4f39-8990-a56f8411582e,http://www.wikidata.org/entity/Q1017599,BSP Business & Law School,Berlin,Berlin,[DE],https://www.businessschool-berlin.de/,NaN,university,businessschool-berlin.de,...,52.406958,2026-05-08 15:30:11.685839,"[mx-hh.mail-bz.de, mx-ber.mail-bz.de]","[220 mx-hh.mail-bz.de - NoSpamProxy ready, 220...","[VERSATEL, DE]",[],[VERSATEL],DE,high,self-hosted
3,bef4aea6-6ff7-4ab9-a562-23c24309d4a0,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,[DE],http://www.cvjm-hochschule.de/,NaN,university,cvjm-hochschule.de,...,51.303670,2026-05-08 15:30:11.685839,"[mx2.serve-me.de, mx1.serve-me.de]","[220 mx2.serve-me.de ESMTP, 220 mx1.serve-me.d...","[HETZNER-AS, DE]",[esmtp],[HETZNER-AS],DE,high,self-hosted
4,76eb7cc0-0321-43a4-a8ee-522dc3172a46,http://www.wikidata.org/entity/Q1060,Technische Universität Hamburg,Hamburg,Hamburg,[DE],https://www.tuhh.de/,NaN,university,tuhh.de,...,53.460958,2026-05-08 15:30:11.685839,"[smtp3.rz.tu-harburg.de, smtp4.rz.tu-harburg.d...",[220-smtp3.rz.tu-harburg.de ESMTP Postfix (Deb...,[DFN Verein zur Foerderung eines Deutschen For...,"[postfix, esmtp]",[DFN Verein zur Foerderung eines Deutschen For...,DE,high,self-hosted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,db56a6e0-a38c-4745-aec6-4e2397a0dc43,http://www.wikidata.org/entity/Q78,Basel,Basel,NaN,[CH],https://www.bs.ch/,NaN,city,bs.ch,...,47.560556,2026-05-08 15:30:11.685839,"[mail.swisscom.com, mail20.swisscom.com, mail1...",[220 mail.swisscom.com ESMTP Service Swisscom ...,"[SWISSCOM Swisscom Switzerland Ltd, CH]",[esmtp],[SWISSCOM Swisscom Switzerland Ltd],CH,medium,self-hosted
5008,41ade22b-becb-4763-b1b0-af2a6b472c78,http://www.wikidata.org/entity/Q807,Lausanne,Lausanne,NaN,[CH],https://www.lausanne.ch/,NaN,city,lausanne.ch,...,46.533333,2026-05-08 15:30:11.685839,[mxvdl.lausanne.ch],"[220 lsamgwp03.lausanne.ch ESMTP Smtpd; Mon, 1...","[SIL-CITYCABLE-AS, CH]",[esmtp],[SIL-CITYCABLE-AS],CH,medium,self-hosted
5009,83f3c00c-5800-489f-8af9-0e6798f22610,http://www.wikidata.org/entity/Q9009,Schaffhausen,Schaffhausen,NaN,[CH],https://www.stadt-schaffhausen.ch/,NaN,city,stadt-schaffhausen.ch,...,47.696530,2026-05-08 15:30:11.685839,"[miraculix2.ksd.ch, miraculix1.ksd.ch]","[554-miraculix2.ksd.ch, 554-miraculix1.ksd.ch]","[KSD, CH]",[],[KSD],CH,medium,self-hosted
5010,aca98be5-3763-4199-9b48-a633e1a03434,http://www.wikidata.org/entity/Q9093,Bülach,Bülach,NaN,"[US, CH, GB]",https://www.buelach.ch,NaN,city,buelach.ch,...,47.518889,2026-05-08 15:30:11.685839,"[buelach-ch.mail.protection.outlook.com, mailp...",[220 DB1PEPF000509ED.mail.protection.outlook.c...,[MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpo...,"[microsoft_smtp, esmtp]",[MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpo...,CH,low,hyperscaler
5011,a54a81f3-7eac-4eeb-a58a-481d6e7a2e5e,http://www.wikidata.org/entity/Q9125,Winterthur,Winterthur,NaN,None,https://stadt.winterthur.ch,NaN,city,stadt.winterthur.ch,...,47.499200,2026-05-08 15:30:11.685839,None,None,None,[],[],[],medium,self-hosted

In [5]:
df_copy = df.copy()

drop = [
    "uuid", "id", "city", "state", "website", "email", "website_domain", "mx", "smtp", "asn", "country"
]

rename = {
    "name":"org",
    "website_domain":"domain",
    "category_tag":"category",
    "longitude":"lon",
    "latitude":"lat",
    "timestamp":"last_checked",
}

df_copy.drop(columns=drop, inplace=True)
df_copy.rename(columns=rename, inplace=True)
df_copy.to_dict(orient="records")

[{'org': 'Duale Hochschule Baden-Württemberg Lörrach',
  'category': 'university',
  'lon': 7.67724,
  'lat': 47.61733,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['BELWUE BelWue-Koordination'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Burg Giebichenstein Kunsthochschule Halle',
  'category': 'university',
  'lon': 11.9549,
  'lat': 51.5027,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['HLKOMM 04107 Leipzig'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'BSP Business & Law School',
  'category': 'university',
  'lon': 13.054074,
  'lat': 52.406958,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['VERSATEL'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'CVJM-Hochschule',
  'category': 'university',
  'lon': 9.41451,
  'lat': 51.30367,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['HETZNER-AS'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Technische Universität Hamburg',
  'category': 'university',
  'lon': 9.969506,
  'lat': 53.460958,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'BSBI School of Business and Innovation',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['IRONPORT-SYSTEMS-INC - Cisco Systems Ironport Division'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'self-hosted'},
 {'org': 'University of Labour',
  'category': 'university',
  'lon': 8.67197,
  'lat': 50.130408,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Charlotte Fresenius Hochschule',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'SRH University Campus Fürth',
  'category': 'university',
  'lon': 10.99784,
  'lat': 49.45966,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Collegium Borromaeum (Freiburg im Breisgau)',
  'category': 'university',
  'lon': 7.854624,
  'lat': 47.995091,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['MIMECAST-DE'],
  'provider_country': 'GB',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Collegium Orientale',
  'category': 'university',
  'lon': 11.1857,
  'lat': 48.8906,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Collegium Willibaldinum',
  'category': 'university',
  'lon': 11.185966,
  'lat': 48.890658,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Rheinland-Pfälzische Technische Universität Kaiserslautern-Landau',
  'category': 'university',
  'lon': 7.75246,
  'lat': 49.42483,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['UNIKL',
   'DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'CBS International Business School',
  'category': 'university',
  'lon': 6.949167,
  'lat': 50.924444,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['COLT COLT Technology Services Group Limited'],
  'provider_country': 'GB',
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Universität Koblenz',
  'category': 'university',
  'lon': 7.558333,
  'lat': 50.363611,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['RLP-NET'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Diploma Hochschule',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Katholisch-Theologische Fakultät der Universität Erfurt',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Humanistische Hochschule Berlin',
  'category': 'university',
  'lon': 13.399307,
  'lat': 52.575401,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['GD-EMEA-DC-CGN1',
   'MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Europäische Hochschule für Innovation und Perspektive',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Centre juridique franco-allemand',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp', 'exchange'],
  'provider': ['INFOMANIAK-AS'],
  'provider_country': 'CH',
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Design akademie berlin, SRH Hochschule für Kommunikation und Design',
  'category': 'university',
  'lon': 13.434686,
  'lat': 52.49214,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Deutsche Hochschule der Polizei',
  'category': 'university',
  'lon': 7.645,
  'lat': 51.8981,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['DTAG Internet service provider operations'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Deutsche Hochschule für Prävention und Gesundheitsmanagement',
  'category': 'university',
  'lon': 7.03634,
  'lat': 49.25076,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['INFOSERVE-AS D-66119 Saarbruecken'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Universität Stuttgart',
  'category': 'university',
  'lon': 9.1752,
  'lat': 48.7817,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['BELWUE BelWue-Koordination'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Berufsakademie für Bankwirtschaft',
  'category': 'university',
  'lon': 9.82683,
  'lat': 52.384382,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Berufsakademie Melle',
  'category': 'university',
  'lon': 8.318105,
  'lat': 52.199395,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Institut für künstlerische Forschung und Bildung München',
  'category': 'university',
  'lon': 11.537318,
  'lat': 48.10281,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['IONOS-AS This is the joint network for IONOS'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Deutsche Internationale Universität Berlin',
  'category': 'university',
  'lon': 13.289577,
  'lat': 52.582121,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Tomorrow University of Applied Sciences (',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['AMAZON-02 - Amazon.com', 'GOOGLE - Google LLC'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Private Berufsakademie Fulda',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['DTAG Internet service provider operations'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Schifffahrtmedizinisches Institut der Marine',
  'category': 'university',
  'lon': 10.094491,
  'lat': 54.339707,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Hochschule der Medien',
  'category': 'university',
  'lon': 9.1012,
  'lat': 48.7408,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['BELWUE BelWue-Koordination'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Steuerakademie Niedersachsen',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Rheinische Hochschule Köln',
  'category': 'university',
  'lon': 6.9419,
  'lat': 50.9799,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Fachhochschule für Finanzen Brandenburg',
  'category': 'university',
  'lon': 13.6153,
  'lat': 52.2926,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Dresden International University',
  'category': 'university',
  'lon': 13.721933,
  'lat': 51.048764,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Fachhochschule Südwestfalen',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'EBC Hochschule',
  'category': 'university',
  'lon': 9.991389,
  'lat': 53.557778,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['IONOS-AS This is the joint network for IONOS'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Karlsruhe',
  'category': 'university',
  'lon': 8.38552,
  'lat': 49.0261,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Heidenheim',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Duale Hochschule Baden-Württemberg',
  'category': 'university',
  'lon': 9.17622,
  'lat': 48.7823,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['MK-NETZDIENSTE-AS', 'SSERV-AS', 'NCORE-AS HKN GmbH'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Mannheim',
  'category': 'university',
  'lon': 8.53472,
  'lat': 49.4744,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['MK-NETZDIENSTE-AS', 'SSERV-AS', 'NCORE-AS HKN GmbH'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Stuttgart',
  'category': 'university',
  'lon': 9.17083,
  'lat': 48.7736,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['sendmail', 'esmtp'],
  'provider': ['BELWUE BelWue-Koordination'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Villingen-Schwenningen',
  'category': 'university',
  'lon': 8.533778,
  'lat': 48.060954,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Mosbach',
  'category': 'university',
  'lon': 9.151305,
  'lat': 49.354158,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['BELWUE BelWue-Koordination'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Duale Hochschule Baden-Württemberg Ravensburg',
  'category': 'university',
  'lon': 9.613434,
  'lat': 47.779846,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': ['MK-NETZDIENSTE-AS', 'SSERV-AS', 'NCORE-AS HKN GmbH'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Medizinische Universität Lausitz – Carl Thiem',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['MNET-AS Germany'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'EBZ Business School',
  'category': 'university',
  'lon': 7.21069,
  'lat': 51.4523,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Hochschule für angewandtes Management',
  'category': 'university',
  'lon': 13.486328,
  'lat': 52.523719,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Technische Universität Ilmenau',
  'category': 'university',
  'lon': 10.93889,
  'lat': 50.68167,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Muthesius Kunsthochschule',
  'category': 'university',
  'lon': 10.1414,
  'lat': 54.3272,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['postfix', 'esmtp'],
  'provider': ['HETZNER-AS'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Einsatzausbildungszentrum Schadensabwehr Marine',
  'category': 'university',
  'lon': 10.80683,
  'lat': 54.09991,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': [],
  'provider': [],
  'provider_country': [],
  'sovereignty_level': 'medium',
  'provider_type': 'self-hosted'},
 {'org': 'Pädagogische Hochschule Karlsruhe',
  'category': 'university',
  'lon': 8.39274,
  'lat': 49.0137,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['AS-IRONP-VEGA - Cisco Systems Ironport Division'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'self-hosted'},
 {'org': 'Munich Business School',
  'category': 'university',
  'lon': 11.524444,
  'lat': 48.136111,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Hochschule Niederrhein',
  'category': 'university',
  'lon': 6.57061,
  'lat': 51.3167,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['esmtp'],
  'provider': ['DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.'],
  'provider_country': 'DE',
  'sovereignty_level': 'high',
  'provider_type': 'self-hosted'},
 {'org': 'Fachhochschule Dortmund',
  'category': 'university',
  'lon': 7.45779,
  'lat': 51.5063,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'Constructor University',
  'category': 'university',
  'lon': 8.65,
  'lat': 53.166667,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'CIU Korntal',
  'category': 'university',
  'lon': nan,
  'lat': nan,
  'last_checked': '2026-05-08 15:30:11.685839',
  'smtp_software': ['microsoft_smtp', 'esmtp'],
  'provider': ['MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corporation'],
  'provider_country': 'US',
  'sovereignty_level': 'low',
  'provider_type': 'hyperscaler'},
 {'org': 'German University of Digital Science',
  'category': 'university',
  'lon': nan,
  'lat': nan,

In [6]:
import json

with open("json_dump.json", "w", encoding="utf-8") as f:
    json.dump(df_copy.to_dict(orient="records"), f, indent=2, ensure_ascii=False)

In [7]:
import json

with open(r"D:\Projekte\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\scanner\cache_dump.json") as f:
    cache_dump = json.load(f)
cache_dump

{'dhbw-loerrach.de': {'errors': {},
  'mx': ['mx4.belwue.de', 'mx2.belwue.de', 'mx1.belwue.de', 'mx3.belwue.de']},
 'burg-halle.de': {'errors': {},
  'mx': ['burg-halle.de'],
  'ip': ['212.122.56.1'],
  'smtp': '220 ****************************************************'},
 'businessschool-berlin.de': {'errors': {},
  'mx': ['mx-hh.mail-bz.de', 'mx-ber.mail-bz.de']},
 'cvjm-hochschule.de': {'errors': {},
  'mx': ['mx2.serve-me.de', 'mx1.serve-me.de']},
 'tuhh.de': {'errors': {},
  'mx': ['smtp3.rz.tu-harburg.de',
   'smtp4.rz.tu-harburg.de',
   'smtp5.rz.tu-harburg.de']},
 'berlinsbi.com': {'errors': {},
  'mx': ['mx1.hc6443-94.iphmx.com', 'mx2.hc6443-94.iphmx.com']},
 'university-of-labour.de': {'errors': {},
  'mx': ['universityoflabour-de02ec.mail.protection.outlook.com']},
 'charlotte-fresenius-uni.de': {'errors': {},
  'mx': ['charlottefreseniusuni-de02c1i.mail.protection.outlook.com']},
 'srh-university.de': {'errors': {},
  'mx': ['srhuniversity-de0i.mail.protection.outlook.com']},
 'cb-freiburg.de': {'errors': {},
  'mx': ['de-smtp-inbound-1.mimecast.com', 'de-smtp-inbound-2.mimecast.com']},
 'collegium-orientale.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: collegium-orientale.de. IN MX'}}},
 'priesterseminar-eichstaett.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: priesterseminar-eichstaett.de. IN MX'}}},
 'rptu.de': {'errors': {},
  'mx': ['mailgate2.uni-kl.de', 'mailgate1.uni-kl.de']},
 'cbs-edu.de': {'errors': {}, 'mx': ['mx1.ews-koeln.de', 'mx2.ews-koeln.de']},
 'uni-koblenz.de': {'errors': {}, 'mx': ['mx.uni-koblenz.de']},
 'diploma.de': {'errors': {},
  'mx': ['diploma-de.mail.protection.outlook.com']},
 'uni-erfurt.de': {'errors': {},
  'mx': ['c1891.mx.srv.dfn.de',
   'mx01.uni-erfurt.de',
   'b1891.mx.srv.dfn.de',
   'mail.uni-erfurt.de',
   'a1891.mx.srv.dfn.de',
   'unie-mailrouter.hs-itz.tu-ilmenau.de']},
 'humanistische-hochschule-berlin.de': {'errors': {},
  'mx': ['humanistischehochschuleberlin-de03c2b.mail.protection.outlook.com',
   'mx0.humanistische-hochschule-berlin.de']},
 'ehip.eu': {'errors': {}, 'mx': ['ehip-eu.mail.protection.outlook.com']},
 'cjfa.eu': {'errors': {}, 'mx': ['mta-gw.infomaniak.ch']},
 'design-akademie-berlin.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: design-akademie-berlin.de. IN MX'}}},
 'dhpol.de': {'errors': {}, 'mx': ['dhpolpost.dhpol.de']},
 'dhfpg.de': {'errors': {}, 'mx': ['mail.dhfpg.de']},
 'uni-stuttgart.de': {'errors': {},
  'mx': ['mxex2.tik.uni-stuttgart.de', 'mxex1.tik.uni-stuttgart.de']},
 'ba-bankwirtschaft.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: ba-bankwirtschaft.de. IN MX'}}},
 'ba-melle.de': {'errors': {},
  'mx': ['bamelle-de0e.mail.protection.outlook.com']},
 'mima-university.de': {'errors': {},
  'mx': ['mx01.ionos.de', 'mx00.ionos.de']},
 'giu-berlin.de': {'errors': {},
  'mx': ['giuberlin-de0i.mail.protection.outlook.com']},
 'tomorrow.university': {'errors': {},
  'mx': ['alt1.aspmx.l.google.com',
   'alt2.aspmx.l.google.com',
   'alt3.aspmx.l.google.com',
   'gmfb72gnaljg6u4krb3bg4npmofme6lwbyomhpomaec6zmcyncva.mx-verification.google.com',
   'feedback-smtp.eu-west-1.amazonses.com',
   'aspmx.l.google.com',
   'alt4.aspmx.l.google.com']},
 'ba-fulda.de': {'errors': {}, 'mx': ['mx.bu-jordan.de']},
 'bundeswehr.de': {'errors': {}, 'mx': ['']},
 'hdm-stuttgart.de': {'errors': {},
  'mx': ['mx3.hdm-stuttgart.de',
   'mx1.hdm-stuttgart.de',
   'mx2.hdm-stuttgart.de',
   'mx4.hdm-stuttgart.de']},
 'steuerakademie.niedersachsen.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: steuerakademie.niedersachsen.de. IN MX'}}},
 'rh-koeln.de': {'errors': {},
  'mx': ['rhkoeln-de0e.mail.protection.outlook.com']},
 'fhf.brandenburg.de': {'errors': {},
  'mx': ['pmmx-hea-p01.brandenburg.de', 'pmmx-hea-p02.brandenburg.de']},
 'di-uni.de': {'errors': {}, 'mx': ['diuni-de0e.mail.protection.outlook.com']},
 'fh-swf.de': {'errors': {},
  'mx': ['itsmx-02.fh-swf.de', 'itsmx-01.fh-swf.de']},
 'ebc-hochschule.de': {'errors': {}, 'mx': ['mx01.ionos.de', 'mx00.ionos.de']},
 'karlsruhe.dhbw.de': {'errors': {}, 'mx': ['']},
 'dhbw-heidenheim.de': {'errors': {},
  'mx': ['dhbwheidenheim-de01b.mail.protection.outlook.com']},
 'dhbw.de': {'errors': {},
  'mx': ['mx02.hornetsecurity.com',
   'mx04.hornetsecurity.com',
   'mx03.hornetsecurity.com',
   'mx01.hornetsecurity.com']},
 'dhbw-mannheim.de': {'errors': {},
  'mx': ['mx03.hornetsecurity.com',
   'mx01.hornetsecurity.com',
   'mx02.hornetsecurity.com',
   'mx04.hornetsecurity.com']},
 'dhbw-stuttgart.de': {'errors': {}, 'mx': ['argonath.dhbw-stuttgart.de']},
 'dhbw-vs.de': {'errors': {'mx': {'type': 'NoNameservers',
    'message': 'All nameservers failed to answer the query dhbw-vs.de. IN MX: Server Do53:192.168.2.1@53 answered SERVFAIL'}}},
 'dhbw-mosbach.de': {'errors': {},
  'mx': ['mx4.belwue.de', 'mx1.belwue.de', 'mx3.belwue.de', 'mx2.belwue.de']},
 'dhbw-ravensburg.de': {'errors': {},
  'mx': ['mx03.hornetsecurity.com',
   'mx02.hornetsecurity.com',
   'mx01.hornetsecurity.com']},
 'mul-ct.de': {'errors': {},
  'mx': ['ctk-mail01.donotspam.de', 'ctk-mail02.donotspam.de']},
 'ebz-business-school.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: ebz-business-school.de. IN MX'}}},
 'fham.de': {'errors': {}, 'mx': ['fham-de.mail.protection.outlook.com']},
 'tu-ilmenau.de': {'errors': {},
  'mx': ['mail-router1.rz.tu-ilmenau.de',
   'b2221.mx.srv.dfn.de',
   'mail-router2.rz.tu-ilmenau.de',
   'a2221.mx.srv.dfn.de',
   'c2221.mx.srv.dfn.de',
   'mail.tu-ilmenau.de']},
 'muthesius-kunsthochschule.de': {'errors': {},
  'mx': ['mx10.planet-ocean.email', 'mx04.planet-ocean.email']},
 'ph-karlsruhe.de': {'errors': {},
  'mx': ['mx2.hc2201-78.eu.iphmx.com', 'mx1.hc2201-78.eu.iphmx.com']},
 'munich-business-school.de': {'errors': {},
  'mx': ['munichbusinessschool-de01e1i.mail.protection.outlook.com']},
 'hs-niederrhein.de': {'errors': {}, 'mx': ['eos.hs-niederrhein.de']},
 'fh-dortmund.de': {'errors': {},
  'mx': ['fhdortmund-de0e.mail.protection.outlook.com']},
 'constructor.university': {'errors': {},
  'mx': ['constructor-university.mail.protection.outlook.com']},
 'ciu.edu': {'errors': {}, 'mx': ['ciu-edu.mail.protection.outlook.com']},
 'german-uds.de': {'errors': {},
  'mx': ['germanuds-de01e.mail.protection.outlook.com',
   'german-uds-de.mail.protection.outlook.com']},
 'eh-ludwigsburg.de': {'errors': {},
  'mx': ['mx2.elk-wue.de', 'mx1.elk-wue.de']},
 'hochschule-macromedia.de': {'errors': {},
  'mx': ['mx00.udag.de', 'mx01.udag.de']},
 'eah-jena.de': {'errors': {},
  'mx': ['b1981.mx.srv.dfn.de', 'c1981.mx.srv.dfn.de', 'a1981.mx.srv.dfn.de']},
 'fhf-nordkirchen.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: fhf-nordkirchen.de. IN MX'}}},
 'eufh.de': {'errors': {}, 'mx': ['eufh-de.mail.protection.outlook.com']},
 'euro-fh.de': {'errors': {},
  'mx': ['eurofh-de01b.mail.protection.outlook.com']},
 'nordakademie.de': {'errors': {},
  'mx': ['nordakademie-de.mail.protection.outlook.com']},
 'efh-bochum.de': {'errors': {},
  'mx': ['a1291.mx.srv.dfn.de', 'b1291.mx.srv.dfn.de', 'c1291.mx.srv.dfn.de']},
 'eh-berlin.de': {'errors': {},
  'mx': ['ehberlin-de0e.mail.protection.outlook.com']},
 'eh-darmstadt.de': {'errors': {},
  'mx': ['ehdarmstadt-de0e.mail.protection.outlook.com']},
 'tpi-moritzburg.de': {'errors': {}, 'mx': ['r84.hostingwerk.de']},
 'eh-tabor.de': {'errors': {},
  'mx': ['ehtabor-de0e.mail.protection.outlook.com']},
 'kirchenmusik-dresden.de': {'errors': {},
  'mx': ['mx01.ionos.de', 'mx00.ionos.de']},
 'kirchenmusikhochschule.de': {'errors': {}, 'mx': ['dedi944.your-server.de']},
 'ehk-halle.de': {'errors': {}, 'mx': ['mx01.ionos.de', 'mx00.ionos.de']},
 'ev-hochschule-hh.de': {'errors': {}, 'mx': ['mx03.eckd.de']},
 'ehs-dresden.de': {'errors': {}, 'mx': ['mail.ehs-dresden.de']},
 'fh-aachen.de': {'errors': {}, 'mx': ['mx1.rz.rwth-aachen.de']},
 'hsbi.de': {'errors': {},
  'mx': ['c2631.mx.srv.dfn.de', 'a2631.mx.srv.dfn.de', 'b2631.mx.srv.dfn.de']},
 'th-brandenburg.de': {'errors': {},
  'mx': ['b1051.mx.srv.dfn.de', 'a1051.mx.srv.dfn.de', 'c1051.mx.srv.dfn.de']},
 'fh-dresden.eu': {'errors': {},
  'mx': ['fhdresden-eu0e.mail.protection.outlook.com']},
 'fh-erfurt.de': {'errors': {},
  'mx': ['a2371.mx.srv.dfn.de', 'b2371.mx.srv.dfn.de', 'c2371.mx.srv.dfn.de']},
 'hs-kl.de': {'errors': {},
  'mx': ['mailgate-1.zdv.net',
   'mailgate-4.zdv.net',
   'mailgate-2.zdv.net',
   'mailgate-3.zdv.net']},
 'fh-kiel.de': {'errors': {'mx': {'type': 'NoNameservers',
    'message': 'All nameservers failed to answer the query fh-kiel.de. IN MX: Server Do53:192.168.2.1@53 answered SERVFAIL'}}},
 'th-luebeck.de': {'errors': {},
  'mx': ['a2471.mx.srv.dfn.de', 'b2471.mx.srv.dfn.de', 'c2471.mx.srv.dfn.de']},
 'hks-ottersberg.de': {'errors': {}, 'mx': ['mx00.ionos.de', 'mx01.ionos.de']},
 'fh-polizei.sachsen-anhalt.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: fh-polizei.sachsen-anhalt.de. IN MX'}}},
 'hs-schmalkalden.de': {'errors': {},
  'mx': ['a1151.mx.srv.dfn.de', 'c1151.mx.srv.dfn.de', 'b1151.mx.srv.dfn.de']},
 'fh-schwetzingen.de': {'errors': {},
  'mx': ['mx00.ionos.de', 'mx01.ionos.de']},
 'hochschule-stralsund.de': {'errors': {},
  'mx': ['a1871.mx.srv.dfn.de', 'b1871.mx.srv.dfn.de', 'c1871.mx.srv.dfn.de']},
 'fh-westkueste.de': {'errors': {},
  'mx': ['a2002.mx.srv.dfn.de', 'b2002.mx.srv.dfn.de', 'c2002.mx.srv.dfn.de']},
 'hs-worms.de': {'errors': {},
  'mx': ['MailGate-02.hs-worms.de',
   'MailGate-03.hs-worms.de',
   'MailGate-01.hs-worms.de']},
 'fh-diakonie.de': {'errors': {}, 'mx': ['mx1.bethel.de', 'mx2.bethel.de']},
 'hpolbb.de': {'errors': {},
  'mx': ['a2861.mx.srv.dfn.de', 'c2861.mx.srv.dfn.de', 'b2861.mx.srv.dfn.de']},
 'fhsv.sachsen.de': {'errors': {},
  'mx': ['s2vg300mr01.pzd-svn.de', 's2vg300mr02.pzd-svn.de']},
 'hsbund.de': {'errors': {}, 'mx': ['mx2.bund.de', 'mx1.bund.de']},
 'fhdw.de': {'errors': {}, 'mx': ['fhdw-de.mail.protection.outlook.com']},
 'fh-mittelstand.de': {'errors': {},
  'mx': ['fhmittelstand-de0e.mail.protection.outlook.com']},
 'fachhochschule-edenkoben.de': {'errors': {},
  'mx': ['mx-a.ktk.de', 'mx-b.ktk.de']},
 'fhr.nrw.de': {'errors': {},
  'mx': ['relay7m.it.nrw.de', 'relay7v.it.nrw.de']},
 'fh-hermannsburg.de': {'errors': {}, 'mx': ['mx20.elm-mission.de']},
 'fhvd.de': {'errors': {}, 'mx': ['mx5.fhvd.de']},
 'phwt.de': {'errors': {}, 'mx': ['mail.phwt.de']},
 'fhdw-hannover.de': {'errors': {},
  'mx': ['fhdwhannover-de01b.mail.protection.outlook.com']},
 'fh-guestrow.de': {'errors': {}, 'mx': ['mx02.mvnet.de', 'mx01.mvnet.de']},
 'hoev-rlp.de': {'errors': {},
  'mx': ['mailmx0002.rlp.de',
   'mailmx0003.rlp.de',
   'mailmx0004.rlp.de',
   'mailmx0001.rlp.de']},
 'hspv.nrw.de': {'errors': {},
  'mx': ['relay7m.it.nrw.de', 'relay7v.it.nrw.de']},
 'hsw-hameln.de': {'errors': {},
  'mx': ['hswhameln-de0i.mail.protection.outlook.com']},
 'muho-mannheim.de': {'errors': {},
  'mx': ['a1234.mx.srv.dfn.de', 'c1234.mx.srv.dfn.de', 'b1234.mx.srv.dfn.de']},
 'fliedner-fachhochschule.de': {'errors': {},
  'mx': ['smail-kwd.dts-security.de']},
 'ph-heidelberg.de': {'errors': {},
  'mx': ['relay.uni-heidelberg.de',
   'relay3.uni-heidelberg.de',
   'relay2.uni-heidelberg.de']},
 'hs-heilbronn.de': {'errors': {},
  'mx': ['hsheilbronn-de0e.mail.protection.outlook.com']},
 'hs-albsig.de': {'errors': {},
  'mx': ['mx2.belwue.de', 'mx3.belwue.de', 'mx1.belwue.de', 'mx4.belwue.de']},
 'ph-freiburg.de': {'errors': {},
  'mx': ['c3041.mx.srv.dfn.de', 'a3041.mx.srv.dfn.de', 'b3041.mx.srv.dfn.de']},
 'rfh-neuss.eu': {'errors': {'mx': {'type': 'NXDOMAIN',
    'message': 'The DNS query name does not exist: rfh-neuss.eu.'}}},
 'freie-hochschule-stuttgart.de': {'errors': {},
  'mx': ['dedi8349.your-server.de']},
 'freie-hochschule-freiburg.de': {'errors': {},
  'mx': ['mail.freie-hochschule-freiburg.de']},
 'fthgiessen.de': {'errors': {}, 'mx': ['mxtls.expurgate.net']},
 'popakademie.de': {'errors': {},
  'mx': ['mx03.hornetsecurity.com',
   'mx02.hornetsecurity.com',
   'mx01.hornetsecurity.com',
   'mx04.hornetsecurity.com']},
 'b-tu.de': {'errors': {}, 'mx': ['smtp-1.b-tu.de', 'smtp-2.b-tu.de']},
 'europa-uni.de': {'errors': {},
  'mx': ['c1611.mx.srv.dfn.de', 'b1611.mx.srv.dfn.de', 'a1611.mx.srv.dfn.de']},
 'th-nuernberg.de': {'errors': {},
  'mx': ['thnuernberg-de0e.mail.protection.outlook.com']},
 'hshl.de': {'errors': {},
  'mx': ['a1971.mx.srv.dfn.de', 'b1971.mx.srv.dfn.de', 'c1971.mx.srv.dfn.de']},
 'polizei.sachsen.de': {'errors': {},
  'mx': ['s2vg300mr01.pzd-svn.de', 's2vg300mr02.pzd-svn.de']},
 'ggs.de': {'errors': {},
  'mx': ['mx1.agenturserver.de', 'mx2.agenturserver.de']},
 'go-bs.de': {'errors': {}, 'mx': ['mxf.bcw-gruppe.de']},
 'uni-heidelberg.de': {'errors': {},
  'mx': ['relay3.uni-heidelberg.de',
   'relay.uni-heidelberg.de',
   'relay2.uni-heidelberg.de']},
 'hu-berlin.de': {'errors': {},
  'mx': ['ir2.cms.hu-berlin.de', 'ir1.cms.hu-berlin.de']},
 'uni-bonn.de': {'errors': {},
  'mx': ['esa2.rhrz.uni-bonn.de',
   'esa3.rhrz.uni-bonn.de',
   'esa1.rhrz.uni-bonn.de']},
 'th-ab.de': {'errors': {},
  'mx': ['b1811.mx.srv.dfn.de', 'a1811.mx.srv.dfn.de', 'c1811.mx.srv.dfn.de']},
 'uni-goettingen.de': {'errors': {},
  'mx': ['a1234.mx.srv.dfn.de', 'b1234.mx.srv.dfn.de', 'c1234.mx.srv.dfn.de']},
 'fu-berlin.de': {'errors': {}, 'mx': ['mail.fu-berlin.de']},
 'uni-potsdam.de': {'errors': {},
  'mx': ['smtpin2.uni-potsdam.de',
   'mx2.uni-potsdam.de',
   'mx1.uni-potsdam.de',
   'smtpin.uni-potsdam.de']},
 'wlh-fuerth.de': {'errors': {}, 'mx': ['mx-74021879.mail.eu.retarus.com']},
 'uni-tuebingen.de': {'errors': {},
  'mx': ['c1541.mx.srv.dfn.de', 'a1541.mx.srv.dfn.de', 'b1541.mx.srv.dfn.de']},
 'uni-freiburg.de': {'errors': {},
  'mx': ['a1421.mx.srv.dfn.de',
   'c1421.mx.srv.dfn.de',
   'mail.uni-freiburg.de',
   'b1421.mx.srv.dfn.de']},
 'hft-stuttgart.de': {'errors': {},
  'mx': ['smtpin02.hft-stuttgart.de', 'smtpin01.hft-stuttgart.de']},
 'gsrn.de': {'errors': {},
  'mx': ['mailgate-2.zdv.net', 'mailgate-3.zdv.net', 'mailgate-1.zdv.net']},
 'uni-jena.de': {'errors': {},
  'mx': ['b2391.mx.srv.dfn.de', 'a2391.mx.srv.dfn.de', 'c2391.mx.srv.dfn.de']},
 'iubh-dualesstudium.de': {'errors': {},
  'mx': ['iubhdualesstudium-de01b.mail.protection.outlook.com']},
 'uni-leipzig.de': {'errors': {},
  'mx': ['v1.rz.uni-leipzig.de',
   'v3.rz.uni-leipzig.de',
   'v2.rz.uni-leipzig.de',
   'v4.rz.uni-leipzig.de']},
 'filmuniversitaet.de': {'errors': {},
  'mx': ['mailrel.filmuniversitaet.de',
   'b1371.mx.srv.dfn.de',
   'a1371.mx.srv.dfn.de',
   'c1371.mx.srv.dfn.de']},
 'uni-marburg.de': {'errors': {},
  'mx': ['a2111.mx.srv.dfn.de', 'b2111.mx.srv.dfn.de', 'c2111.mx.srv.dfn.de']},
 'hawk.de': {'errors': {},
  'mx': ['c2771.mx.srv.dfn.de', 'a2771.mx.srv.dfn.de', 'b2771.mx.srv.dfn.de']},
 'hfh-fernstudium.de': {'errors': {},
  'mx': ['hfhfernstudium-de0i.mail.protection.outlook.com']},
 'uni-hamburg.de': {'errors': {},
  'mx': ['mx03.rrz.uni-hamburg.de',
   'mx04.rrz.uni-hamburg.de',
   'mx05.rrz.uni-hamburg.de']},
 'uni-kiel.de': {'errors': {},
  'mx': ['a2002.mx.srv.dfn.de', 'b2002.mx.srv.dfn.de', 'c2002.mx.srv.dfn.de']},
 'hcu-hamburg.de': {'errors': {},
  'mx': ['smtp3.rz.tu-harburg.de',
   'smtp4.rz.tu-harburg.de',
   'smtp5.rz.tu-harburg.de']},
 'tum.de': {'errors': {}, 'mx': ['postrelay1.lrz.de', 'postrelay2.lrz.de']},
 'dpfa-hs.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: dpfa-hs.de. IN MX'}}},
 'ga-hochschule.de': {'errors': {}, 'mx': ['']},
 'tu-dresden.de': {'errors': {},
  'mx': ['b3011.mx.srv.dfn.de', 'c3011.mx.srv.dfn.de', 'a3011.mx.srv.dfn.de']},
 'hs-doepfer.de': {'errors': {},
  'mx': ['mx04.hornetsecurity.com',
   'mx01.hornetsecurity.com',
   'mx03.hornetsecurity.com',
   'mx02.hornetsecurity.com']},
 'ist-hochschule.de': {'errors': {},
  'mx': ['mx03.hornetsecurity.com',
   'mx04.hornetsecurity.com',
   'mx01.hornetsecurity.com',
   'mx02.hornetsecurity.com']},
 'vwa-hochschule.de': {'errors': {},
  'mx': ['mx2.mail.ovh.net', 'mx1.mail.ovh.net', 'mx3.mail.ovh.net']},
 'tu-chemnitz.de': {'errors': {},
  'mx': ['ezra.hrz.tu-chemnitz.de', 'kyle.hrz.tu-chemnitz.de']},
 'uni-rostock.de': {'errors': {},
  'mx': ['mx1.uni-rostock.de', 'mx2.uni-rostock.de']},
 'hs-ludwigsburg.de': {'errors': {},
  'mx': ['mailgw05.campus-lb.net', 'mailgw04.campus-lb.net']},
 'tiho-hannover.de': {'errors': {},
  'mx': ['a1401.mx.srv.dfn.de', 'b1401.mx.srv.dfn.de', 'c1401.mx.srv.dfn.de']},
 'studienzentrum-rotenburg.de': {'errors': {},
  'mx': ['mx-in-2.hessen.de', 'mx-in-1.hessen.de']},
 'pthv.de': {'errors': {}, 'mx': ['mail.pthv.de']},
 'uni-wuerzburg.de': {'errors': {},
  'mx': ['mailgate2.uni-wuerzburg.de',
   'mailgate3.uni-wuerzburg.de',
   'mailgate1.uni-wuerzburg.de']},
 'uni-mainz.de': {'errors': {},
  'mx': ['mailgate-2.zdv.uni-mainz.de',
   'mailgate-1.zdv.uni-mainz.de',
   'mailgate-3.zdv.uni-mainz.de']},
 'hs21.de': {'errors': {}, 'mx': ['fw.hs21.de']},
 'hs-aalen.de': {'errors': {},
  'mx': ['a3111.mx.srv.dfn.de', 'b3111.mx.srv.dfn.de', 'c3111.mx.srv.dfn.de']},
 'oth-aw.de': {'errors': {}, 'mx': ['smtp.oth-aw.de']},
 'hs-anhalt.de': {'errors': {},
  'mx': ['b1441.mx.srv.dfn.de', 'c1441.mx.srv.dfn.de', 'a1441.mx.srv.dfn.de']},
 'hs-ansbach.de': {'errors': {},
  'mx': ['postrelay2.lrz.de', 'postrelay1.lrz.de']},
 'hochschule-bochum.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: hochschule-bochum.de. IN MX'}}},
 'hochschule-biberach.de': {'errors': {'mx': {'type': 'NoNameservers',
    'message': 'All nameservers failed to answer the query hochschule-biberach.de. IN MX: Server Do53:192.168.2.1@53 answered SERVFAIL'}}},
 'h-brs.de': {'errors': {},
  'mx': ['mx02.h-brs.de', 'mx03.h-brs.de', 'mx01.h-brs.de', 'mx04.h-brs.de']},
 'hs-bremen.de': {'errors': {},
  'mx': ['fmail3.hs-bremen.de', 'fmail1.hs-bremen.de', 'fmail2.hs-bremen.de']},
 'hs-bremerhaven.de': {'errors': {},
  'mx': ['a2981.mx.srv.dfn.de', 'c2981.mx.srv.dfn.de', 'b2981.mx.srv.dfn.de']},
 'hs-emden-leer.de': {'errors': {},
  'mx': ['hsemdenleer-de0e1b.mail.protection.outlook.com']},
 'hs-fresenius.de': {'errors': {},
  'mx': ['hsfresenius-de0e.mail.protection.outlook.com']},
 'hs-esslingen.de': {'errors': {}, 'mx': ['mx01.hs-esslingen.de']},
 'hs-harz.de': {'errors': {},
  'mx': ['a1781.mx.srv.dfn.de', 'c1781.mx.srv.dfn.de', 'b1781.mx.srv.dfn.de']},
 'hof-university.de': {'errors': {},
  'mx': ['hofuniversity-de0i.mail.protection.outlook.com']},
 'thi.de': {'errors': {}, 'mx': ['thi-de.mail.protection.outlook.com']},
 'hochschule-kempten.de': {'errors': {}, 'mx': ['mailin.hs-kempten.de']},
 'hs-koblenz.de': {'errors': {}, 'mx': ['mailgate.hs-koblenz.de']},
 'htwg-konstanz.de': {'errors': {},
  'mx': ['mx2.belwue.de', 'mx3.belwue.de', 'mx4.belwue.de', 'mx1.belwue.de']},
 'hs-lausitz.de': {'errors': {}, 'mx': ['smtp-3.b-tu.de', 'smtp-4.b-tu.de']},
 'haw-landshut.de': {'errors': {},
  'mx': ['postrelay2.lrz.de', 'postrelay1.lrz.de']},
 'hs-magdeburg.de': {'errors': {},
  'mx': ['b1321.mx.srv.dfn.de', 'c1321.mx.srv.dfn.de', 'a1321.mx.srv.dfn.de']},
 'hwg-lu.de': {'errors': {},
  'mx': ['mailgate-2.zdv.net', 'mailgate-3.zdv.net', 'mailgate-1.zdv.net']},
 'hs-merseburg.de': {'errors': {},
  'mx': ['mx2.hs-merseburg.de', 'mx1.hs-merseburg.de']},
 'hnu.de': {'errors': {},
  'mx': ['a2281.mx.srv.dfn.de', 'b2281.mx.srv.dfn.de', 'c2281.mx.srv.dfn.de']},

In [8]:
scan_df = pd.DataFrame.from_dict(cache_dump, orient="index")
scan_df

,errors,mx,ip,smtp,asn
dhbw-loerrach.de,{},"[mx4.belwue.de, mx2.belwue.de, mx1.belwue.de, ...",NaN,NaN,NaN
burg-halle.de,{},[burg-halle.de],[212.122.56.1],220 ******************************************...,NaN
businessschool-berlin.de,{},"[mx-hh.mail-bz.de, mx-ber.mail-bz.de]",NaN,NaN,NaN
cvjm-hochschule.de,{},"[mx2.serve-me.de, mx1.serve-me.de]",NaN,NaN,NaN
tuhh.de,{},"[smtp3.rz.tu-harburg.de, smtp4.rz.tu-harburg.d...",NaN,NaN,NaN
...,...,...,...,...,...
85.218.125.235,{},NaN,NaN,NaN,"{'asn': '34781', 'owner': 'SIL-CITYCABLE-AS, C..."
195.14.126.81,{},NaN,NaN,NaN,"{'asn': '50849', 'owner': 'ASN-LUGA, CH', 'pre..."
195.14.126.82,{},NaN,NaN,NaN,"{'asn': '50849', 'owner': 'ASN-LUGA, CH', 'pre..."
193.200.220.149,{},NaN,NaN,NaN,"{'asn': '34781', 'owner': 'SIL-CITYCABLE-AS, C..."
213.221.234.85,{},NaN,NaN,NaN,"{'asn': '15600', 'owner': 'QUICKLINE Quickline..."

In [9]:
df_mx = pd.merge(df, scan_df["mx"], left_on="website_domain",right_index=True)
df_mx

,uuid,id,name,city,state,country,website,email,category_tag,website_domain,...,timestamp,mx_x,smtp,asn,smtp_software,provider,provider_country,sovereignty_level,provider_type,mx_y
0,b8381380-f672-4c15-a743-fe0ce1509ffe,http://www.wikidata.org/entity/Q1001338,Duale Hochschule Baden-Württemberg Lörrach,Lörrach,Baden-Württemberg,[DE],http://www.dhbw-loerrach.de/,NaN,university,dhbw-loerrach.de,...,2026-05-08 15:30:11.685839,"[mx4.belwue.de, mx2.belwue.de, mx1.belwue.de, ...","[220 mail-in04.belwue.de ESMTP Postfix, 220 ma...","[BELWUE BelWue-Koordination, DE]","[postfix, esmtp]",[BELWUE BelWue-Koordination],DE,high,self-hosted,"[mx4.belwue.de, mx2.belwue.de, mx1.belwue.de, ..."
1,a32648ed-7586-4ed4-9946-80adb13ccedb,http://www.wikidata.org/entity/Q1011953,Burg Giebichenstein Kunsthochschule Halle,Halle (Saale),Sachsen-Anhalt,[DE],https://www.burg-halle.de/,NaN,university,burg-halle.de,...,2026-05-08 15:30:11.685839,[burg-halle.de],[220 *****************************************...,"[HLKOMM 04107 Leipzig, DE]",[],[HLKOMM 04107 Leipzig],DE,high,self-hosted,[burg-halle.de]
2,cf712634-996a-4f39-8990-a56f8411582e,http://www.wikidata.org/entity/Q1017599,BSP Business & Law School,Berlin,Berlin,[DE],https://www.businessschool-berlin.de/,NaN,university,businessschool-berlin.de,...,2026-05-08 15:30:11.685839,"[mx-hh.mail-bz.de, mx-ber.mail-bz.de]","[220 mx-hh.mail-bz.de - NoSpamProxy ready, 220...","[VERSATEL, DE]",[],[VERSATEL],DE,high,self-hosted,"[mx-hh.mail-bz.de, mx-ber.mail-bz.de]"
3,bef4aea6-6ff7-4ab9-a562-23c24309d4a0,http://www.wikidata.org/entity/Q1024571,CVJM-Hochschule,Kassel,Hessen,[DE],http://www.cvjm-hochschule.de/,NaN,university,cvjm-hochschule.de,...,2026-05-08 15:30:11.685839,"[mx2.serve-me.de, mx1.serve-me.de]","[220 mx2.serve-me.de ESMTP, 220 mx1.serve-me.d...","[HETZNER-AS, DE]",[esmtp],[HETZNER-AS],DE,high,self-hosted,"[mx2.serve-me.de, mx1.serve-me.de]"
4,76eb7cc0-0321-43a4-a8ee-522dc3172a46,http://www.wikidata.org/entity/Q1060,Technische Universität Hamburg,Hamburg,Hamburg,[DE],https://www.tuhh.de/,NaN,university,tuhh.de,...,2026-05-08 15:30:11.685839,"[smtp3.rz.tu-harburg.de, smtp4.rz.tu-harburg.d...",[220-smtp3.rz.tu-harburg.de ESMTP Postfix (Deb...,[DFN Verein zur Foerderung eines Deutschen For...,"[postfix, esmtp]",[DFN Verein zur Foerderung eines Deutschen For...,DE,high,self-hosted,"[smtp3.rz.tu-harburg.de, smtp4.rz.tu-harburg.d..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,db56a6e0-a38c-4745-aec6-4e2397a0dc43,http://www.wikidata.org/entity/Q78,Basel,Basel,NaN,[CH],https://www.bs.ch/,NaN,city,bs.ch,...,2026-05-08 15:30:11.685839,"[mail.swisscom.com, mail20.swisscom.com, mail1...",[220 mail.swisscom.com ESMTP Service Swisscom ...,"[SWISSCOM Swisscom Switzerland Ltd, CH]",[esmtp],[SWISSCOM Swisscom Switzerland Ltd],CH,medium,self-hosted,"[mail.swisscom.com, mail20.swisscom.com, mail1..."
5008,41ade22b-becb-4763-b1b0-af2a6b472c78,http://www.wikidata.org/entity/Q807,Lausanne,Lausanne,NaN,[CH],https://www.lausanne.ch/,NaN,city,lausanne.ch,...,2026-05-08 15:30:11.685839,[mxvdl.lausanne.ch],"[220 lsamgwp03.lausanne.ch ESMTP Smtpd; Mon, 1...","[SIL-CITYCABLE-AS, CH]",[esmtp],[SIL-CITYCABLE-AS],CH,medium,self-hosted,[mxvdl.lausanne.ch]
5009,83f3c00c-5800-489f-8af9-0e6798f22610,http://www.wikidata.org/entity/Q9009,Schaffhausen,Schaffhausen,NaN,[CH],https://www.stadt-schaffhausen.ch/,NaN,city,stadt-schaffhausen.ch,...,2026-05-08 15:30:11.685839,"[miraculix2.ksd.ch, miraculix1.ksd.ch]","[554-miraculix2.ksd.ch, 554-miraculix1.ksd.ch]","[KSD, CH]",[],[KSD],CH,medium,self-hosted,"[miraculix2.ksd.ch, miraculix1.ksd.ch]"
5010,aca98be5-3763-4199-9b48-a633e1a03434,http://www.wikidata.org/entity/Q9093,Bülach,Bülach,NaN,"[US, CH, GB]",https://www.buelach.ch,NaN,city,buelach.ch,...,2026-05-08 15:30:11.685839,"[buelach-ch.mail.protection.outlook.com, mailp...",[220 DB1PEPF000509ED.mail.protection.outlook.c...,[MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpo...,"[microsoft_smtp, esmtp]",[MICROSOFT-CORP-MSN-AS-BLOCK - Microsoft Corpo...,CH,low,hyperscaler,"[buelach-ch.mail.protection.outlook.com, mailp..."
5011,a54a81f3-7eac-4eeb-a58a-481d6e7a2e5e,http://www.wikidata.org/entity/Q9125,Winterthur,Winterthur,NaN,None,https://stadt.winterthur.ch,NaN,city,stadt.winterthur.ch,...,2026-05-08 15:30:11.685839,None,None,None,[],[],[],medium,self-hosted,NaN

In [10]:
def map_ips_to_mx(data):
    """
    Mappt IPs zu ihren MX-Records.
    
    Für jeden Eintrag mit MX-Records wird geschaut, ob die MX-Domains
    selbst im Dictionary vorhanden sind, und wenn ja, werden ihre IPs zugeordnet.
    
    Args:
        data: Dictionary mit der beschriebenen Struktur
        
    Returns:
        Dictionary mit Mapping von MX-Domain -> IPs
    """
    mx_to_ip = {}
    
    for domain, info in data.items():
        # Prüfen ob MX-Records vorhanden sind
        if "mx" not in info:
            continue
            
        # Durch alle MX-Records iterieren
        for mx_domain in info["mx"]:
            # Prüfen ob der MX-Domain selbst im Datensatz vorhanden ist
            if mx_domain in data and "ip" in data[mx_domain]:
                # IPs des MX-Servers zuordnen
                mx_to_ip[mx_domain] = data[mx_domain]["ip"]
    
    return mx_to_ip


# Erweiterte Version: IPs direkt in die Struktur einfügen
def enrich_mx_with_ips(data):
    """
    Reichert MX-Records mit ihren IPs an.
    
    Ersetzt MX-Einträge durch Dictionaries mit Domain und zugehörigen IPs.
    
    Args:
        data: Dictionary mit der beschriebenen Struktur
        
    Returns:
        Modifiziertes Dictionary (in-place Änderung)
    """
    result = data.copy()
    
    for domain, info in result.items():
        if "mx" not in info:
            continue
            
        # Neue MX-Liste mit IPs erstellen
        enriched_mx = []
        for mx_domain in info["mx"]:
            mx_entry = {"domain": mx_domain, "ips": []}
            
            # IPs hinzufügen falls vorhanden
            if mx_domain in result and "ip" in result[mx_domain]:
                mx_entry["ips"] = result[mx_domain]["ip"]
            
            enriched_mx.append(mx_entry)
        
        result[domain]["mx"] = enriched_mx
    
    return result


# Verwendung:
mx_to_ip_mapping = map_ips_to_mx(cache_dump)
# Oder:
enriched_data = enrich_mx_with_ips(cache_dump)
enriched_data

{'dhbw-loerrach.de': {'errors': {},
  'mx': [{'domain': 'mx4.belwue.de',
    'ips': ['2001:7c0:0:76::4',
     '2001:7c0:0:76::3',
     '129.143.76.4',
     '129.143.76.3']},
   {'domain': 'mx2.belwue.de', 'ips': ['129.143.76.2', '2001:7c0:0:76::2']},
   {'domain': 'mx1.belwue.de',
    'ips': ['2001:7c0:0:76::1',
     '129.143.76.2',
     '2001:7c0:0:76::2',
     '129.143.76.1']},
   {'domain': 'mx3.belwue.de', 'ips': ['2001:7c0:0:76::3', '129.143.76.3']}]},
 'burg-halle.de': {'errors': {},
  'mx': [{'domain': 'burg-halle.de', 'ips': ['212.122.56.1']}],
  'ip': ['212.122.56.1'],
  'smtp': '220 ****************************************************'},
 'businessschool-berlin.de': {'errors': {},
  'mx': [{'domain': 'mx-hh.mail-bz.de', 'ips': ['83.135.251.162']},
   {'domain': 'mx-ber.mail-bz.de', 'ips': ['62.214.51.13']}]},
 'cvjm-hochschule.de': {'errors': {},
  'mx': [{'domain': 'mx2.serve-me.de', 'ips': ['88.99.236.4']},
   {'domain': 'mx1.serve-me.de', 'ips': ['5.9.228.145']}]},
 'tuhh.de': {'errors': {},
  'mx': [{'domain': 'smtp3.rz.tu-harburg.de',
    'ips': ['2001:638:702:20aa::205:37', '134.28.205.37']},
   {'domain': 'smtp4.rz.tu-harburg.de',
    'ips': ['2001:638:702:20aa::205:34', '134.28.205.34']},
   {'domain': 'smtp5.rz.tu-harburg.de',
    'ips': ['134.28.205.35', '2001:638:702:20aa::205:35']}]},
 'berlinsbi.com': {'errors': {},
  'mx': [{'domain': 'mx1.hc6443-94.iphmx.com',
    'ips': ['68.232.130.72', '68.232.137.67']},
   {'domain': 'mx2.hc6443-94.iphmx.com',
    'ips': ['68.232.130.72', '68.232.137.67']}]},
 'university-of-labour.de': {'errors': {},
  'mx': [{'domain': 'universityoflabour-de02ec.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '52.101.170.1',
     '2a01:111:f403:ca2d::1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'charlotte-fresenius-uni.de': {'errors': {},
  'mx': [{'domain': 'charlottefreseniusuni-de02c1i.mail.protection.outlook.com',
    'ips': ['52.101.68.36', '52.101.68.0', '52.101.73.28', '52.101.73.6']}]},
 'srh-university.de': {'errors': {},
  'mx': [{'domain': 'srhuniversity-de0i.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::8',
     '52.101.68.3',
     '2a01:111:f403:ca09::b',
     '2a01:111:f403:ca04::2',
     '52.101.73.26',
     '52.101.73.12',
     '2a01:111:f403:ca04::5',
     '52.101.73.6']}]},
 'cb-freiburg.de': {'errors': {},
  'mx': [{'domain': 'de-smtp-inbound-1.mimecast.com',
    'ips': ['194.104.108.22', '194.104.110.22']},
   {'domain': 'de-smtp-inbound-2.mimecast.com',
    'ips': ['194.104.108.22', '194.104.110.22']}]},
 'collegium-orientale.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: collegium-orientale.de. IN MX'}}},
 'priesterseminar-eichstaett.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: priesterseminar-eichstaett.de. IN MX'}}},
 'rptu.de': {'errors': {},
  'mx': [{'domain': 'mailgate2.uni-kl.de',
    'ips': ['131.246.120.209', '2001:638:208:120::209']},
   {'domain': 'mailgate1.uni-kl.de',
    'ips': ['2001:638:208:120::208', '131.246.120.208']}]},
 'cbs-edu.de': {'errors': {},
  'mx': [{'domain': 'mx1.ews-koeln.de', 'ips': ['62.96.16.3']},
   {'domain': 'mx2.ews-koeln.de', 'ips': ['62.96.16.4']}]},
 'uni-koblenz.de': {'errors': {},
  'mx': [{'domain': 'mx.uni-koblenz.de',
    'ips': ['141.26.8.103', '2001:4c80:50::867']}]},
 'diploma.de': {'errors': {},
  'mx': [{'domain': 'diploma-de.mail.protection.outlook.com',
    'ips': ['52.101.68.0',
     '2a01:111:f403:ca04::f',
     '2a01:111:f403:ca09::c',
     '2a01:111:f403:ca04::b',
     '2a01:111:f403:ca04::e',
     '52.101.68.36',
     '52.101.73.28',
     '52.101.73.6']}]},
 'uni-erfurt.de': {'errors': {},
  'mx': [{'domain': 'c1891.mx.srv.dfn.de',
    'ips': ['2001:638:d:c303:acdc:1979:2:7a', '194.95.238.148']},
   {'domain': 'mx01.uni-erfurt.de', 'ips': ['194.95.117.162']},
   {'domain': 'b1891.mx.srv.dfn.de',
    'ips': ['194.95.234.148', '2001:638:d:c302:acdc:1979:2:7a']},
   {'domain': 'mail.uni-erfurt.de', 'ips': ['194.95.117.219']},
   {'domain': 'a1891.mx.srv.dfn.de',
    'ips': ['2001:638:d:c301:acdc:1979:2:7a', '194.95.232.148']},
   {'domain': 'unie-mailrouter.hs-itz.tu-ilmenau.de',
    'ips': ['141.24.179.49']}]},
 'humanistische-hochschule-berlin.de': {'errors': {},
  'mx': [{'domain': 'humanistischehochschuleberlin-de03c2b.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '52.101.170.1',
     '2a01:111:f403:ca2d::1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']},
   {'domain': 'mx0.humanistische-hochschule-berlin.de',
    'ips': ['80.237.138.5']}]},
 'ehip.eu': {'errors': {},
  'mx': [{'domain': 'ehip-eu.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'cjfa.eu': {'errors': {},
  'mx': [{'domain': 'mta-gw.infomaniak.ch',
    'ips': ['83.166.143.57',
     '2001:1600:0:aaaa::1:3',
     '2001:1600:0:aaaa::1:4',
     '83.166.143.58']}]},
 'design-akademie-berlin.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: design-akademie-berlin.de. IN MX'}}},
 'dhpol.de': {'errors': {},
  'mx': [{'domain': 'dhpolpost.dhpol.de', 'ips': ['93.240.132.20']}]},
 'dhfpg.de': {'errors': {},
  'mx': [{'domain': 'mail.dhfpg.de', 'ips': ['212.89.141.166']}]},
 'uni-stuttgart.de': {'errors': {},
  'mx': [{'domain': 'mxex2.tik.uni-stuttgart.de',
    'ips': ['2001:7c0:2041:24::a:2', '129.69.192.21']},
   {'domain': 'mxex1.tik.uni-stuttgart.de',
    'ips': ['2001:7c0:2041:24::a:1', '129.69.192.20']}]},
 'ba-bankwirtschaft.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: ba-bankwirtschaft.de. IN MX'}}},
 'ba-melle.de': {'errors': {},
  'mx': [{'domain': 'bamelle-de0e.mail.protection.outlook.com',
    'ips': ['52.101.68.3',
     '2a01:111:f403:ca09::c',
     '2a01:111:f403:ca09::4',
     '2a01:111:f403:ca04::10',
     '52.101.73.26',
     '2a01:111:f403:ca04::',
     '52.101.73.12',
     '52.101.73.6']}]},
 'mima-university.de': {'errors': {},
  'mx': [{'domain': 'mx01.ionos.de', 'ips': ['217.72.192.67']},
   {'domain': 'mx00.ionos.de', 'ips': ['212.227.15.41']}]},
 'giu-berlin.de': {'errors': {},
  'mx': [{'domain': 'giuberlin-de0i.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'tomorrow.university': {'errors': {},
  'mx': [{'domain': 'alt1.aspmx.l.google.com',
    'ips': ['172.253.152.26', '2a00:1450:4010:c22::1a']},
   {'domain': 'alt2.aspmx.l.google.com',
    'ips': ['192.178.211.27', '2404:6800:4000:1025::1a']},
   {'domain': 'alt3.aspmx.l.google.com',
    'ips': ['2404:6800:4003:c26::1b', '172.253.158.26']},
   {'domain': 'gmfb72gnaljg6u4krb3bg4npmofme6lwbyomhpomaec6zmcyncva.mx-verification.google.com',
    'ips': []},
   {'domain': 'feedback-smtp.eu-west-1.amazonses.com',
    'ips': ['18.200.42.95', '34.243.41.226', '34.250.195.198']},
   {'domain': 'aspmx.l.google.com',
    'ips': ['2a00:1450:4001:c21::1a', '142.251.127.26']},
   {'domain': 'alt4.aspmx.l.google.com',
    'ips': ['108.177.125.26', '2404:6800:4008:c01::1a']}]},
 'ba-fulda.de': {'errors': {},
  'mx': [{'domain': 'mx.bu-jordan.de', 'ips': ['217.92.66.24']}]},
 'bundeswehr.de': {'errors': {}, 'mx': [{'domain': '', 'ips': []}]},
 'hdm-stuttgart.de': {'errors': {},
  'mx': [{'domain': 'mx3.hdm-stuttgart.de', 'ips': ['141.62.16.24']},
   {'domain': 'mx1.hdm-stuttgart.de', 'ips': ['141.62.16.22']},
   {'domain': 'mx2.hdm-stuttgart.de', 'ips': ['141.62.16.23']},
   {'domain': 'mx4.hdm-stuttgart.de', 'ips': ['141.62.16.25']}]},
 'steuerakademie.niedersachsen.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: steuerakademie.niedersachsen.de. IN MX'}}},
 'rh-koeln.de': {'errors': {},
  'mx': [{'domain': 'rhkoeln-de0e.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::9',
     '52.101.68.0',
     '2a01:111:f403:ca09::9',
     '2a01:111:f403:ca04::d',
     '2a01:111:f403:ca09::4',
     '52.101.68.36',
     '52.101.73.28',
     '52.101.73.6']}]},
 'fhf.brandenburg.de': {'errors': {},
  'mx': [{'domain': 'pmmx-hea-p01.brandenburg.de', 'ips': ['194.76.232.119']},
   {'domain': 'pmmx-hea-p02.brandenburg.de', 'ips': ['194.76.232.120']}]},
 'di-uni.de': {'errors': {},
  'mx': [{'domain': 'diuni-de0e.mail.protection.outlook.com',
    'ips': ['52.101.68.3',
     '2a01:111:f403:ca09::c',
     '2a01:111:f403:ca09::4',
     '2a01:111:f403:ca04::',
     '52.101.73.26',
     '2a01:111:f403:ca04::10',
     '52.101.73.12',
     '52.101.73.6']}]},
 'fh-swf.de': {'errors': {},
  'mx': [{'domain': 'itsmx-02.fh-swf.de', 'ips': ['193.174.68.52']},
   {'domain': 'itsmx-01.fh-swf.de', 'ips': ['193.174.68.51']}]},
 'ebc-hochschule.de': {'errors': {},
  'mx': [{'domain': 'mx01.ionos.de', 'ips': ['217.72.192.67']},
   {'domain': 'mx00.ionos.de', 'ips': ['212.227.15.41']}]},
 'karlsruhe.dhbw.de': {'errors': {}, 'mx': [{'domain': '', 'ips': []}]},
 'dhbw-heidenheim.de': {'errors': {},
  'mx': [{'domain': 'dhbwheidenheim-de01b.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::1',
     '2a01:111:f403:ca09::',
     '52.101.73.16',
     '2a01:111:f403:ca09::7',
     '52.101.68.25',
     '2a01:111:f403:ca04::e',
     '52.101.68.12',
     '52.101.68.10']}]},
 'dhbw.de': {'errors': {},
  'mx': [{'domain': 'mx02.hornetsecurity.com', 'ips': ['94.100.136.8']},
   {'domain': 'mx04.hornetsecurity.com', 'ips': ['94.100.136.7']},
   {'domain': 'mx03.hornetsecurity.com', 'ips': ['94.100.134.8']},
   {'domain': 'mx01.hornetsecurity.com', 'ips': ['94.100.132.8']}]},
 'dhbw-mannheim.de': {'errors': {},
  'mx': [{'domain': 'mx03.hornetsecurity.com', 'ips': ['94.100.134.8']},
   {'domain': 'mx01.hornetsecurity.com', 'ips': ['94.100.132.8']},
   {'domain': 'mx02.hornetsecurity.com', 'ips': ['94.100.136.8']},
   {'domain': 'mx04.hornetsecurity.com', 'ips': ['94.100.136.7']}]},
 'dhbw-stuttgart.de': {'errors': {},
  'mx': [{'domain': 'argonath.dhbw-stuttgart.de', 'ips': ['141.31.41.200']}]},
 'dhbw-vs.de': {'errors': {'mx': {'type': 'NoNameservers',
    'message': 'All nameservers failed to answer the query dhbw-vs.de. IN MX: Server Do53:192.168.2.1@53 answered SERVFAIL'}}},
 'dhbw-mosbach.de': {'errors': {},
  'mx': [{'domain': 'mx4.belwue.de',
    'ips': ['2001:7c0:0:76::4',
     '2001:7c0:0:76::3',
     '129.143.76.4',
     '129.143.76.3']},
   {'domain': 'mx1.belwue.de',
    'ips': ['2001:7c0:0:76::1',
     '129.143.76.2',
     '2001:7c0:0:76::2',
     '129.143.76.1']},
   {'domain': 'mx3.belwue.de', 'ips': ['2001:7c0:0:76::3', '129.143.76.3']},
   {'domain': 'mx2.belwue.de', 'ips': ['129.143.76.2', '2001:7c0:0:76::2']}]},
 'dhbw-ravensburg.de': {'errors': {},
  'mx': [{'domain': 'mx03.hornetsecurity.com', 'ips': ['94.100.134.8']},
   {'domain': 'mx02.hornetsecurity.com', 'ips': ['94.100.136.8']},
   {'domain': 'mx01.hornetsecurity.com', 'ips': ['94.100.132.8']}]},
 'mul-ct.de': {'errors': {},
  'mx': [{'domain': 'ctk-mail01.donotspam.de', 'ips': ['212.18.1.58']},
   {'domain': 'ctk-mail02.donotspam.de', 'ips': ['212.18.21.84']}]},
 'ebz-business-school.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: ebz-business-school.de. IN MX'}}},
 'fham.de': {'errors': {},
  'mx': [{'domain': 'fham-de.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'tu-ilmenau.de': {'errors': {},
  'mx': [{'domain': 'mail-router1.rz.tu-ilmenau.de', 'ips': ['141.24.179.34']},
   {'domain': 'b2221.mx.srv.dfn.de', 'ips': ['194.95.234.182']},
   {'domain': 'mail-router2.rz.tu-ilmenau.de', 'ips': ['141.24.179.35']},
   {'domain': 'a2221.mx.srv.dfn.de', 'ips': ['194.95.232.182']},
   {'domain': 'c2221.mx.srv.dfn.de', 'ips': ['194.95.238.182']},
   {'domain': 'mail.tu-ilmenau.de',
    'ips': ['141.24.179.35', '141.24.4.8', '141.24.179.34']}]},
 'muthesius-kunsthochschule.de': {'errors': {},
  'mx': [{'domain': 'mx10.planet-ocean.email',
    'ips': ['2a01:4f8:251:8ae::e', '157.90.140.108']},
   {'domain': 'mx04.planet-ocean.email',
    'ips': ['178.63.254.83', '2a01:4f8:231:3054::e']}]},
 'ph-karlsruhe.de': {'errors': {},
  'mx': [{'domain': 'mx2.hc2201-78.eu.iphmx.com',
    'ips': ['23.90.105.149', '207.54.67.167']},
   {'domain': 'mx1.hc2201-78.eu.iphmx.com',
    'ips': ['23.90.105.149', '207.54.67.167']}]},
 'munich-business-school.de': {'errors': {},
  'mx': [{'domain': 'munichbusinessschool-de01e1i.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca09::',
     '52.101.68.39',
     '52.101.73.16',
     '2a01:111:f403:ca04::7',
     '2a01:111:f403:ca04::f',
     '52.101.73.19',
     '2a01:111:f403:ca04::10',
     '52.101.73.1']}]},
 'hs-niederrhein.de': {'errors': {},
  'mx': [{'domain': 'eos.hs-niederrhein.de', 'ips': ['194.94.120.22']}]},
 'fh-dortmund.de': {'errors': {},
  'mx': [{'domain': 'fhdortmund-de0e.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'constructor.university': {'errors': {},
  'mx': [{'domain': 'constructor-university.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca09::2',
     '2a01:111:f403:ca09::d',
     '52.101.73.16',
     '52.101.68.8',
     '52.101.68.16',
     '2a01:111:f403:ca04::c',
     '2a01:111:f403:ca04::b',
     '52.101.73.12']}]},
 'ciu.edu': {'errors': {},
  'mx': [{'domain': 'ciu-edu.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:f903::',
     '52.101.41.183',
     '2a01:111:f403:f901::',
     '52.101.50.1',
     '2a01:111:f403:c931::1',
     '52.101.10.10',
     '52.101.41.22',
     '2a01:111:f403:f908::']}]},
 'german-uds.de': {'errors': {},
  'mx': [{'domain': 'germanuds-de01e.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca09::1',
     '2a01:111:f403:ca04::f',
     '2a01:111:f403:ca04::d',
     '52.101.73.11',
     '52.101.68.16',
     '2a01:111:f403:ca04::2',
     '52.101.68.5',
     '52.101.73.22']},
   {'domain': 'german-uds-de.mail.protection.outlook.com', 'ips': []}]},
 'eh-ludwigsburg.de': {'errors': {},
  'mx': [{'domain': 'mx2.elk-wue.de', 'ips': ['194.59.169.11']},
   {'domain': 'mx1.elk-wue.de', 'ips': ['194.59.169.21']}]},
 'hochschule-macromedia.de': {'errors': {},
  'mx': [{'domain': 'mx00.udag.de', 'ips': ['62.146.106.39']},
   {'domain': 'mx01.udag.de', 'ips': ['62.146.106.40']}]},
 'eah-jena.de': {'errors': {},
  'mx': [{'domain': 'b1981.mx.srv.dfn.de', 'ips': ['194.95.234.147']},
   {'domain': 'c1981.mx.srv.dfn.de', 'ips': ['194.95.238.147']},
   {'domain': 'a1981.mx.srv.dfn.de', 'ips': ['194.95.232.147']}]},
 'fhf-nordkirchen.de': {'errors': {'mx': {'type': 'NoAnswer',
    'message': 'The DNS response does not contain an answer to the question: fhf-nordkirchen.de. IN MX'}}},
 'eufh.de': {'errors': {},
  'mx': [{'domain': 'eufh-de.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca09::',
     '2a01:111:f403:ca04::7',
     '52.101.73.6',
     '52.101.73.26',
     '52.101.68.25',
     '2a01:111:f403:ca04::6',
     '52.101.73.2',
     '2a01:111:f403:ca09::e']}]},
 'euro-fh.de': {'errors': {},
  'mx': [{'domain': 'eurofh-de01b.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'nordakademie.de': {'errors': {},
  'mx': [{'domain': 'nordakademie-de.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::1',
     '2a01:111:f403:ca09::',
     '52.101.68.12',
     '52.101.73.16',
     '2a01:111:f403:ca09::7',
     '52.101.68.10',
     '2a01:111:f403:ca04::e',
     '52.101.68.25']}]},
 'efh-bochum.de': {'errors': {},
  'mx': [{'domain': 'a1291.mx.srv.dfn.de', 'ips': ['194.95.232.67']},
   {'domain': 'b1291.mx.srv.dfn.de', 'ips': ['194.95.234.67']},
   {'domain': 'c1291.mx.srv.dfn.de', 'ips': ['194.95.238.67']}]},
 'eh-berlin.de': {'errors': {},
  'mx': [{'domain': 'ehberlin-de0e.mail.protection.outlook.com',
    'ips': ['52.101.68.3',
     '2a01:111:f403:ca09::c',
     '2a01:111:f403:ca09::4',
     '2a01:111:f403:ca04::',
     '2a01:111:f403:ca04::10',
     '52.101.73.26',
     '52.101.73.12',
     '52.101.73.6']}]},
 'eh-darmstadt.de': {'errors': {},
  'mx': [{'domain': 'ehdarmstadt-de0e.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::a',
     '52.101.73.1',
     '52.101.68.15',
     '2a01:111:f403:ca04::b',
     '2a01:111:f403:ca04::',
     '52.101.73.26',
     '52.101.68.29',
     '2a01:111:f403:ca09::e']}]},
 'tpi-moritzburg.de': {'errors': {},
  'mx': [{'domain': 'r84.hostingwerk.de',
    'ips': ['2a01:4f8:1c1e:e71e::1', '116.202.184.120']}]},
 'eh-tabor.de': {'errors': {},
  'mx': [{'domain': 'ehtabor-de0e.mail.protection.outlook.com',
    'ips': ['52.101.168.0',
     '2a01:111:f403:ca27::',
     '2a01:111:f403:ca2d::2',
     '2a01:111:f403:ca2d::1',
     '52.101.170.1',
     '2a01:111:f403:ca2d::',
     '52.101.170.2',
     '52.101.170.0']}]},
 'kirchenmusik-dresden.de': {'errors': {},
  'mx': [{'domain': 'mx01.ionos.de', 'ips': ['217.72.192.67']},
   {'domain': 'mx00.ionos.de', 'ips': ['212.227.15.41']}]},
 'kirchenmusikhochschule.de': {'errors': {},
  'mx': [{'domain': 'dedi944.your-server.de',
    'ips': ['2a01:4f8:d0a:32ce::2', '78.46.3.144']}]},
 'ehk-halle.de': {'errors': {},
  'mx': [{'domain': 'mx01.ionos.de', 'ips': ['217.72.192.67']},
   {'domain': 'mx00.ionos.de', 'ips': ['212.227.15.41']}]},
 'ev-hochschule-hh.de': {'errors': {},
  'mx': [{'domain': 'mx03.eckd.de', 'ips': ['193.58.253.233']}]},
 'ehs-dresden.de': {'errors': {},
  'mx': [{'domain': 'mail.ehs-dresden.de', 'ips': ['62.214.13.131']}]},
 'fh-aachen.de': {'errors': {},
  'mx': [{'domain': 'mx1.rz.rwth-aachen.de', 'ips': ['137.226.78.57']}]},
 'hsbi.de': {'errors': {},
  'mx': [{'domain': 'c2631.mx.srv.dfn.de', 'ips': ['194.95.239.33']},
   {'domain': 'a2631.mx.srv.dfn.de', 'ips': ['194.95.233.33']},
   {'domain': 'b2631.mx.srv.dfn.de', 'ips': ['194.95.235.33']}]},
 'th-brandenburg.de': {'errors': {},
  'mx': [{'domain': 'b1051.mx.srv.dfn.de', 'ips': ['194.95.234.38']},
   {'domain': 'a1051.mx.srv.dfn.de', 'ips': ['194.95.232.38']},
   {'domain': 'c1051.mx.srv.dfn.de', 'ips': ['194.95.238.38']}]},
 'fh-dresden.eu': {'errors': {},
  'mx': [{'domain': 'fhdresden-eu0e.mail.protection.outlook.com',
    'ips': ['2a01:111:f403:ca04::9',
     '52.101.68.0',
     '2a01:111:f403:ca09::9',
     '2a01:111:f403:ca04::d',
     '2a01:111:f403:ca09::4',
     '52.101.68.36',
     '52.101.73.28',
     '52.101.73.6']}]},
 'fh-erfurt.de': {'errors': {},
  'mx': [{'domain': 'a2371.mx.srv.dfn.de', 'ips': ['194.95.232.199']},
   {'domain': 'b2371.mx.srv.dfn.de', 'ips': ['194.95.234.199']},
   {'domain': 'c2371.mx.srv.dfn.de', 'ips': ['194.95.238.199']}]},
 'hs-kl.de': {'errors': {},
  'mx': [{'domain': 'mailgate-1.zdv.net',
    'ips': ['134.93.178.241', '2001:4c80:40:62d::25:1']},
   {'domain': 'mailgate-4.zdv.net', 'ips': []},
   {'domain': 'mailgate-2.zdv.net',
    'ips': ['2001:4c80:40:62d::25:2', '134.93.178.242']},
   {'domain': 'mailgate-3.zdv.net',
    'ips': ['2001:4c80:40:62d::25:3', '134.93.178.243']}]},

In [11]:



def df_to_json(df: pd.DataFrame, path: str):
    rename_cols = {
        "name":"org",
        "website_domain":"domain",
        "category_tag":"category",
        "longitude":"lon",
        "latitude":"lat",
    }

    df.rename(columns=rename_cols, inplace=True)
    return df.to_json(orient="records")

df_to_json(df.sample(20), "")

'[{"uuid":"8774c70d-6417-4466-953a-e471022a85cf","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q480646","org":"Amtsgericht D\\u00fclmen","city":"D\\u00fclmen","state":"Nordrhein-Westfalen","country":["DE"],"website":"http:\\/\\/www.ag-duelmen.nrw.de\\/","email":null,"category":"courthouse","domain":"ag-duelmen.nrw.de","lon":7.27864,"lat":51.8321,"timestamp":"2026-05-08 15:30:11.685839","mx":["relay7m.it.nrw.de","relay7v.it.nrw.de"],"smtp":["220 relay7m.it.nrw.de ESMTP Postfix","220 relay7v.it.nrw.de ESMTP Postfix"],"asn":["IT-NRW, DE"],"smtp_software":["postfix","esmtp"],"provider":["IT-NRW"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"96f3fbe2-9790-4545-ba6b-bbb50c847d4c","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q572512","org":"Teltow","city":"Teltow","state":"Brandenburg","country":["DE"],"website":"https:\\/\\/www.teltow.de\\/","email":null,"category":"city","domain":"teltow.de","lon":13.270556,"lat":52.402222,"timestamp":"2026-05-08 15:30:11.685839","mx":["mailsec.teltow.de"],"smtp":["554 No SMTPd here   202605102322530047786;1"],"asn":["DTAG Internet service provider operations, DE"],"smtp_software":[],"provider":["DTAG Internet service provider operations"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"012c3b9b-6471-4072-a0bc-9c5adfe87fa8","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q2478851","org":"Umwelt-Campus Birkenfeld","city":null,"state":"Rheinland-Pfalz","country":["DE"],"website":"http:\\/\\/www.umwelt-campus.de\\/ucb\\/index.php?id=home&L=1","email":null,"category":"university","domain":"umwelt-campus.de","lon":7.16917,"lat":49.6078,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx1.umwelt-campus.de","mx4.umwelt-campus.de"],"smtp":["220 mx1.umwelt-campus.de ESMTP Postfix","220 mx4.umwelt-campus.de"],"asn":["RLP-NET, DE"],"smtp_software":["postfix","esmtp"],"provider":["RLP-NET"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"543de83b-8802-47b4-bcd9-6d9d12051739","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q145008","org":"St. Blasien","city":"St. Blasien","state":"Baden-W\\u00fcrttemberg","country":["DE"],"website":"https:\\/\\/www.stblasien.de\\/","email":null,"category":"city","domain":"stblasien.de","lon":8.128333,"lat":47.761945,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx6.kvnbw.de","mx9.kvnbw.de","mx7.kvnbw.de","mx8.kvnbw.de"],"smtp":["220 mx6.kvnbw.de ESMTP Postfix","220 mx9.kvnbw.de ESMTP Postfix","220 mx7.kvnbw.de ESMTP Postfix","220 mx8.kvnbw.de ESMTP Postfix"],"asn":["KOMM-ONE-AS, DE"],"smtp_software":["postfix","esmtp"],"provider":["KOMM-ONE-AS"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"24c188cb-2545-4744-b68f-743327fe397b","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q37833463","org":"St. Vinzenz-Krankenhaus Hanau","city":"Hanau","state":"Hessen","country":["DE"],"website":"https:\\/\\/vinzenz-hanau.de\\/","email":"mailto:info@vinzenz-hanau.de","category":"hospital","domain":"vinzenz-hanau.de","lon":8.91226,"lat":50.13497,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx1.st-vinzenz-fulda.de","mx2.st-vinzenz-fulda.de"],"smtp":["554-mx1.st-vinzenz-fulda.de","554-mx2.st-vinzenz-fulda.de"],"asn":["NETHINKS-AS NETHINKS GmbH, DE"],"smtp_software":[],"provider":["NETHINKS-AS NETHINKS GmbH"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"76a19312-faa6-4092-93cc-f1e94b32bec8","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q25392389","org":"Amtsgericht Frankfurt\\/Oder","city":"Frankfurt (Oder)","state":"Brandenburg","country":null,"website":"http:\\/\\/www.ag-frankfurt-oder.brandenburg.de\\/","email":null,"category":"courthouse","domain":"ag-frankfurt-oder.brandenburg.de","lon":null,"lat":null,"timestamp":"2026-05-08 15:30:11.685839","mx":null,"smtp":null,"asn":null,"smtp_software":[],"provider":[],"provider_country":[],"sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"462a3ae4-674d-4c56-ba66-9935f318af58","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q540107","org":"Waldeck","city":"Waldeck","state":"Hessen","country":["DE"],"website":"https:\\/\\/www.waldeck-stadt.de\\/","email":null,"category":"city","domain":"waldeck-stadt.de","lon":9.066667,"lat":51.2,"timestamp":"2026-05-08 15:30:11.685839","mx":["smtpin.rzone.de"],"smtp":["220 smtpin.rzone.de ESMTP RZmta 55.0.1 ready (mi86)"],"asn":["STRATO STRATO AG, DE"],"smtp_software":["esmtp"],"provider":["STRATO STRATO AG"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"2f7b663b-f773-419d-9bdf-cfcbc965377b","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q565504","org":"Hatzfeld","city":"Hatzfeld","state":"Hessen","country":null,"website":"https:\\/\\/www.hatzfeldeder.de\\/","email":null,"category":"city","domain":"hatzfeldeder.de","lon":8.55,"lat":51.0,"timestamp":"2026-05-08 15:30:11.685839","mx":null,"smtp":null,"asn":null,"smtp_software":[],"provider":[],"provider_country":[],"sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"d62360c3-1bf2-49f7-943c-82e03c92708f","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q319333","org":"Stiftungsuniversit\\u00e4t Hildesheim","city":"Hildesheim","state":"Niedersachsen","country":["DE"],"website":"https:\\/\\/www.uni-hildesheim.de\\/","email":null,"category":"university","domain":"uni-hildesheim.de","lon":9.975,"lat":52.133333,"timestamp":"2026-05-08 15:30:11.685839","mx":["robin.uni-hildesheim.de","batman.uni-hildesheim.de"],"smtp":["220 robin.uni-hildesheim.de ready at  Mon, 11 May 2026 01:21:55 +0200","220 batman.uni-hildesheim.de ready at  Mon, 11 May 2026 01:21:55 +0200"],"asn":["DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE"],"smtp_software":[],"provider":["DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V."],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"1b3891a1-64db-4412-9c74-3d2de8c12a63","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q682739","org":"Johannes-Kepler-Universit\\u00e4t","city":"Linz","state":null,"country":["AT"],"website":"https:\\/\\/www.jku.at\\/","email":null,"category":"university","domain":"jku.at","lon":14.3175,"lat":48.3375,"timestamp":"2026-05-08 15:30:11.685839","mx":["mail3.edvz.uni-linz.ac.at","mail4.edvz.uni-linz.ac.at","mail1.edvz.uni-linz.ac.at","mail2.edvz.uni-linz.ac.at"],"smtp":null,"asn":["ACONET ACOnet Backbone, AT","JKU-LINZ-AS University Linz, AT"],"smtp_software":[],"provider":["ACONET ACOnet Backbone","JKU-LINZ-AS University Linz"],"provider_country":"AT","sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"e4d69843-b8e3-4c6f-86a7-68f4b824b85c","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q1602176","org":"Sch\\u00f6n Klinik Hamburg Eilbek","city":"Hamburg","state":"Hamburg","country":["FR"],"website":"http:\\/\\/www.schoen-kliniken.de\\/ptp\\/kkh\\/eil\\/","email":null,"category":"hospital","domain":"schoen-kliniken.de","lon":10.053889,"lat":53.577222,"timestamp":"2026-05-08 15:30:11.685839","mx":["smgc012mx-sk.smg.atos-services.net","smgc011mx-sk.smg.atos-services.net"],"smtp":["554-smgc012mx-sk.smg.atos-services.net","554-smgc011mx-sk.smg.atos-services.net"],"asn":["INACDE-ATOS, DE"],"smtp_software":[],"provider":["INACDE-ATOS"],"provider_country":"DE","sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"f509856a-8457-4402-9024-a1f87010b81a","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q7032","org":"Filderstadt","city":"Filderstadt","state":"Baden-W\\u00fcrttemberg","country":["DE"],"website":"http:\\/\\/www.filderstadt.de\\/","email":null,"category":"city","domain":"filderstadt.de","lon":9.216667,"lat":48.666667,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx8.kvnbw.de","mx6.kvnbw.de","mx7.kvnbw.de","mx9.kvnbw.de"],"smtp":["220 mx8.kvnbw.de ESMTP Postfix","220 mx6.kvnbw.de ESMTP Postfix","220 mx7.kvnbw.de ESMTP Postfix","220 mx9.kvnbw.de ESMTP Postfix"],"asn":["KOMM-ONE-AS, DE"],"smtp_software":["postfix","esmtp"],"provider":["KOMM-ONE-AS"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"67b858a9-dff5-4bec-9035-1c5da8236e32","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q480904","org":"Amtsgericht Neresheim","city":"Neresheim","state":"Baden-W\\u00fcrttemberg","country":null,"website":"https:\\/\\/amtsgericht-neresheim.justiz-bw.de\\/","email":null,"category":"courthouse","domain":"amtsgericht-neresheim.justiz-bw.de","lon":10.3367,"lat":48.753,"timestamp":"2026-05-08 15:30:11.685839","mx":null,"smtp":null,"asn":null,"smtp_software":[],"provider":[],"provider_country":[],"sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"2efbeba7-28f1-4519-93ef-5e86d60113f0","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q58566","org":"Bodenwerder","city":"Bodenwerder","state":"Niedersachsen","country":["DE"],"website":"https:\\/\\/www.muenchhausenland.de\\/portal\\/seiten\\/bodenwerder-900000008-25640.html","email":null,"category":"city","domain":"muenchhausenland.de","lon":9.516667,"lat":51.966667,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx01.nol-is.de","mx00.nol-is.de"],"smtp":["220 mx01.nol-is.de ESMTP Hi!","220 mx00.nol-is.de ESMTP Hi!"],"asn":["MYLOC-AS WIIT group IP Backbone, DE"],"smtp_software":["esmtp"],"provider":["MYLOC-AS WIIT group IP Backbone"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"ad065f82-7c22-47e9-9862-3e3c4d23c5fe","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q10743","org":"B\\u00f6hlen","city":"B\\u00f6hlen","state":"Sachsen","country":["DE"],"website":"https:\\/\\/www.stadt-boehlen.de\\/","email":null,"category":"city","domain":"stadt-boehlen.de","lon":12.385968,"lat":51.202728,"timestamp":"2026-05-08 15:30:11.685839","mx":["s2vg300mr02.pzd-svn.de","s2vg300mr01.pzd-svn.de"],"smtp":null,"asn":["SUB-LIR-SN-AS Sub-LIR SN, DE"],"smtp_software":[],"provider":["SUB-LIR-SN-AS Sub-LIR SN"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"0aea5391-afc6-47a4-ae65-2fa8a37df6d0","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q374159","org":"Hecklingen","city":"Hecklingen","state":"Sachsen-Anhalt","country":["DE"],"website":"https:\\/\\/www.stadt-hecklingen.de\\/","email":null,"category":"city","domain":"stadt-hecklingen.de","lon":11.516667,"lat":51.85,"timestamp":"2026-05-08 15:30:11.685839","mx":["mail.stadt-hecklingen.de"],"smtp":["220-mail.stadt-hecklingen.de ESMTP Proxmox"],"asn":["DTAG Internet service provider operations, DE"],"smtp_software":["esmtp"],"provider":["DTAG Internet service provider operations"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"40916569-a2fd-4d67-9e2a-a2432726402d","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q165140","org":"Herrnhut","city":"Herrnhut","state":"Sachsen","country":["DE"],"website":"https:\\/\\/www.herrnhut.de\\/","email":null,"category":"city","domain":"herrnhut.de","lon":14.741667,"lat":51.016667,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx.dsinet.de"],"smtp":["220 mx02.dsinet.de ESMTP Postfix (Debian\\/GNU)"],"asn":["DSINET-ASN, DE"],"smtp_software":["postfix","esmtp"],"provider":["DSINET-ASN"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"},{"uuid":"80784195-28c1-4dff-b186-0e6051e485dc","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q138348361","org":"Bezirkskrankenhaus Schwaz","city":null,"state":null,"country":["AT"],"website":"https:\\/\\/www.kh-schwaz.at","email":null,"category":"hospital","domain":"kh-schwaz.at","lon":11.705,"lat":47.345,"timestamp":"2026-05-08 15:30:11.685839","mx":["extmail2.tirol-kliniken.at","extmail1.tirol-kliniken.at"],"smtp":["220 mail.tirol-kliniken.at ESMTP Mon, 11 May 2026 01:22:26 +0200","220 mail.tirol-kliniken.at ESMTP Mon, 11 May 2026 01:22:26 +0200"],"asn":["ACONET ACOnet Backbone, AT"],"smtp_software":["esmtp"],"provider":["ACONET ACOnet Backbone"],"provider_country":"AT","sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"384c09c9-8a27-4fb1-ba0a-89a70f880fc8","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q106824954","org":"Bezirkskrankenhaus Reutte","city":null,"state":null,"country":["AT"],"website":"https:\\/\\/www.bkh-reutte.at","email":null,"category":"hospital","domain":"bkh-reutte.at","lon":10.713112,"lat":47.473422,"timestamp":"2026-05-08 15:30:11.685839","mx":["mail.bkh-reutte.at"],"smtp":["220 mail.bkh-reutte.at ESMTP Smtpd; Mon, 11 May 2026 01:22:24 +0200"],"asn":["UTA-AS, AT"],"smtp_software":["esmtp"],"provider":["UTA-AS"],"provider_country":"AT","sovereignty_level":"medium","provider_type":"self-hosted"},{"uuid":"1b80a12c-05ee-419d-9574-a38d0258b050","id":"http:\\/\\/www.wikidata.org\\/entity\\/Q480780","org":"Amtsgericht Husum","city":"Husum","state":"Schleswig-Holstein","country":["DE"],"website":"https:\\/\\/www.schleswig-holstein.de\\/DE\\/justiz\\/gerichte-und-justizbehoerden\\/AmtsgerichteSH\\/AGHusum\\/AGHusum_node.html","email":null,"category":"courthouse","domain":"schleswig-holstein.de","lon":9.05378,"lat":54.4809,"timestamp":"2026-05-08 15:30:11.685839","mx":["mx1.landsh.de","mx2.landsh.de"],"smtp":["220-mx1.landsh.de ESMTP Postfix","220-mx2.landsh.de ESMTP Postfix"],"asn":["DATAPORT-AS, DE"],"smtp_software":["postfix","esmtp"],"provider":["DATAPORT-AS"],"provider_country":"DE","sovereignty_level":"high","provider_type":"self-hosted"}]'